### ISSUE TITLE
Showing issue while generating protobuf file for YOLOv2

### ISSUE THREAD

**Issue by spaul13** [thtrieu/darkflow#1014]
While generating protobuf file for yolov2 (using weight and cfg file). I am getting the following error

_**flow --model cfg/yolov2.cfg --load yolov2.weights --savepb**
Parsing ./cfg/yolov2.cfg
Parsing cfg/yolov2.cfg
Loading yolov2.weights ...
Successfully identified 203934260 bytes
Finished in 0.0162749290466s
Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/sj/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/sj/darkflow/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/sj/darkflow/darkflow/net/build.py", line 64, in __init__
    self.framework = create_framework(*args)
  File "/home/sj/darkflow/darkflow/net/framework.py", line 59, in create_framework
    return this(meta, FLAGS)
  File "/home/sj/darkflow/darkflow/net/framework.py", line 15, in __init__
    self.constructor(meta, FLAGS)
  File "/home/sj/darkflow/darkflow/net/yolo/__init__.py", line 24, in constructor
    ).format(meta['model'])
AssertionError: labels.txt and cfg/yolov2.cfg indicate inconsistent class numbers_

Can anyone please tell me whether I need to change the labels.txt or anything to make this work?

**Comment by ayermolo** [comment]
Rename your cfg file with the same name as dark flow one, or provide the label file manually. My understanding Darkflow matches the name to what is in github and uses hard coded labels, otherwise looks in to labels.txt file.
