### ISSUE TITLE
Referring:- Training on your own dataset

### ISSUE THREAD

**Issue by pardeep3december** [thtrieu/darkflow#1032]
I am referring Training on your own dataset getting following error.
Windwos 8.1 , python 3.7

[train.zip](https://github.com/thtrieu/darkflow/files/3124722/train.zip)

##############################################
C:\work\darkflow-master>pip3 list
##############################################
Package              Version
-------------------- --------
absl-py              0.7.1
asn1crypto           0.24.0
astor                0.7.1
boost                0.1
certifi              2019.3.9
cffi                 1.12.3
chardet              3.0.4
cmake                3.13.3
cryptography         2.6.1
Cython               0.29.7
darkflow             1.0.0
decorator            4.4.0
gast                 0.2.2
grpcio               1.20.0
h5py                 2.9.0
http-ece             1.1.0
idna                 2.8
imutils              0.5.2
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
Markdown             3.1
Mastodon.py          1.3.1
mock                 2.0.0
numpy                1.16.2
opencv-python        3.4.2.16
pbr                  5.1.3
Pillow               6.0.0
pip                  19.1
protobuf             3.7.1
pycparser            2.19
python-dateutil      2.8.0
pytz                 2019.1
requests             2.21.0
scipy                1.2.1
setuptools           41.0.1
six                  1.12.0
SQLAlchemy           1.3.3
tensorboard          1.13.1
tensorflow           1.13.1
tensorflow-estimator 1.13.0
termcolor            1.1.0
urllib3              1.24.2
Werkzeug             0.15.2
wheel                0.33.1

C:\work\darkflow-master>python  flow --model cfg/tiny-yolo-voc-1c.cfg  --load bi
n/yolov2-tiny-voc.weights --train --annotation new_model_data/nnotations --datas
et new_model/data/images --epoch 300

Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\work\darkflow-master\darkflow\cli.py", line 3, in <module>
    from .net.build import TFNet
  File "C:\work\darkflow-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, i
n <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", lin
e 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

C:\work\darkflow-master>
##################################################

**Comment by syedimad1998** [comment]
@pardeep3december install cuda and tensor flow-gpu properly 
follow this article- https://medium.com/@Oysiyl/install-tensorflow-1-13-on-ubuntu-18-04-with-gpu-support-239b36d29070
