### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by Mikkochu** [thtrieu/darkflow#1129]
I'm getting the following error. I have tensorflow installed and I have access to the folders in my project

https://imgur.com/a/io3Abaf

```
C:\Users\Mikko\PycharmProjects\Darknet_project\venv\Scripts\python.exe C:/Users/Mikko/PycharmProjects/Darknet_project/Main.py
2020-01-19 15:39:46.219944: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-19 15:39:46.220073: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:/Users/Mikko/PycharmProjects/Darknet_project/Main.py", line 2, in <module>
    from darkflow.net.build import TFNet     #Tfnet is a class in build.py python files through which  Translate darknet to tensorflow.
  File "C:\Users\Mikko\PycharmProjects\Darknet_project\darkflow-master\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "C:\Users\Mikko\PycharmProjects\Darknet_project\darkflow-master\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "C:\Users\Mikko\PycharmProjects\Darknet_project\darkflow-master\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by Mikkochu** [comment]
Installed tensorflow 1.3.1 and got this to work

**Comment by RubeVi17** [comment]
@Mikkochu where did you downloaded 1.3.1 version?

**Comment by arunasank** [comment]
@RubeVi17 `pip install tensorflow==1.13.0 tensorflow-gpu==1.13.0`

**Comment by ozgurdogan646** [comment]
@arunasank I got this error when I tried.

```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0
```
