### ISSUE TITLE
Build Cython for fast YOLOv2

### ISSUE THREAD

**Issue by ramarajan09** [thtrieu/darkflow#124]
I tried to clone the latest code with cython update and try build 
cd ./cython_utils
python3 setup.py build_ext --inplace

I get the following error, any help?
![error](https://cloud.githubusercontent.com/assets/26741040/24576875/236ed748-16b3-11e7-9663-9f70c1e4c3c4.png)

**Comment by Prakash19921206** [comment]
i'm having same error!

**Comment by Dhruv-Mohan** [comment]
Hmm , I don't have a windows system to test this on. Can you replace the code in setup.py with

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
import numpy

ext_modules=[
    Extension("cy_yolo2_findboxes",
              sources=["cy_yolo2_findboxes.pyx"],
              #libraries=["m"], # Unix-like specific
			  include_dirs=[numpy.get_include()]
    )
]



setup(

    name= 'cy_yolo2_findboxes',
    ext_modules = cythonize(ext_modules),
)
```

and report back, with the time the box_constructor function takes to execute ?

**Comment by ramarajan09** [comment]
Great! that works I can compile now. @Dhruv-Mohan

**Comment by Dhruv-Mohan** [comment]
@ramarajan09  can you also tell me the time box_constructor takes to execute? 
look in yolov2->test.py for the function

**Comment by ramarajan09** [comment]
how would I run that function alone?

**Comment by Dhruv-Mohan** [comment]
I'll add the changes for windows specific building, as soon as i've debugged the cythonised yolov1 models

**Comment by eljefedelrodeodeljefe** [comment]
I have the same problem on OS X. Theoretically the includes should be resolved, but they aren't.

**Comment by eljefedelrodeodeljefe** [comment]
This solves it (on OS X), as I apparently header locations of numpy don't get passed through. No expert with a real solution though... 
```
python3 setup.py build_ext --inplace --include-dirs=/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include
```

**Comment by EmmanouelP** [comment]
Running the setup command on windows  gave me the below error.Does it have to do with my c++ compiler or what?Any solution to this?

python setup.py build_ext --inplace
running build_ext
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    ext_modules = cythonize(ext_modules)
  File "C:\Users\manolis\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\manolis\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\manolis\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\manolis\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Users\manolis\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\manolis\Anaconda3\lib\distutils\command\build_ext.py", line 307, in run
    force=self.force)
  File "C:\Users\manolis\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\manolis\Anaconda3\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\manolis\Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "C:\Users\manolis\Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900

**Comment by thtrieu** [comment]
Original Issue is resolved.
