### ISSUE TITLE
fine-tuning error

### ISSUE THREAD

**Issue by imian00** [thtrieu/darkflow#145]
hi guys! I have some problems regarding fine-tuning with my own datasets which i got from Imagenet database.. so it would be very thankful if you guys tell me what i did wrong.

1. my datasets have 5 classes so I editted labels.txt like below :

Chihuahua
beagle
malamute
Pomeranian
miniature_poodle

2.  cfg :

I editted cfg/v1.1/tiny-yolov1.cfg.
changed classes to 5 in [detection], output of [connected] to 735( 7*7*15 ), and also filters of the last [convolutional] to 20 ( num*(5+classes) = 2*10 )

[net]
batch=64
subdivisions=2
height=448
width=448
channels=3
momentum=0.9
decay=0.0005

saturation=.75
exposure=.75
hue = .1

learning_rate=0.0005
policy=steps
steps=200,400,600,800,20000,30000
scales=2.5,2,2,2,.1,.1
max_batches = 40000

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=20
activation=leaky

[connected]
output= 735
activation=linear

[detection]
classes=5
coords=4
rescore=1
side=7
num=2
softmax=0
sqrt=1
jitter=.2

object_scale=1
noobject_scale=.5
class_scale=1
coord_scale=5

3. annotation xml is like :

<annotation>
	<folder>VOC2007</folder>
	<filename>n02085620_7.jpg</filename>
	<source>
		<database>ImageNet database</database>
	</source>
	<size>
		<width>250</width>
		<height>188</height>
		<depth>3</depth>
	</size>
	<segment>0</segment>
	<object>
		<name>Chihuahua</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>71</xmin>
			<ymin>1</ymin>
			<xmax>192</xmax>
			<ymax>180</ymax>
		</bndbox>
	</object>
</annotation>

4. and also the name of the jpeg image files match 1 to 1 with the name of the annotation xml files :
= VOC2007 = JPEGImages = n02085620_7.jpg
                                               .....
                   = Annotations = n02085620_7.xml
                                              ....

5. my command :

python flow --train --model cfg/kong-tiny-yolov1.cfg --dataset D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\VOC2007\JPEGImages --annotation D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\VOC2007\Annotations

6. and the error message :

Parsing cfg/kong-tiny-yolov1.cfg
Loading None ...
Finished in 0.0s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 448, 448, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 448, 448, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 224, 224, 16)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 224, 224, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 112, 112, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 112, 112, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 56, 56, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 56, 56, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 28, 28, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 14, 14, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 7, 7, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 7, 7, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 7, 7, 20)
 Load  |  Yep!  | flat                             | (?, 980)
 Init  |  Yep!  | full 980 x 735  linear           | (?, 735)
-------+--------+----------------------------------+---------------
Running entirely on CPU
cfg/kong-tiny-yolov1.cfg loss hyper-parameters:
        side    = 7
        box     = 2
        classes = 5
        scales  = [1.0, 1.0, 0.5, 5.0]
Building cfg/kong-tiny-yolov1.cfg loss
Building cfg/kong-tiny-yolov1.cfg train op
2017-04-07 16:52:48.651615: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.651795: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.653448: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.653829: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.653869: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.655078: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.656304: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:48.657324: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-04-07 16:52:49.369051: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties:
name: GeForce 940M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-04-07 16:52:49.370144: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:908] DMA: 0
2017-04-07 16:52:49.372788: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:918] 0:   Y
2017-04-07 16:52:49.374611: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940M, pci bus id: 0000:01:00.0)
Finished in 9.251139402389526s

Enter training ...

cfg/kong-tiny-yolov1.cfg parsing D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\VOC2007\Annotations
Parsing for ['Chihuahua', 'beagle', 'malamute', 'Pomeranian', 'miniature_poodle']
[====================>]100%  n02113712_995.xml
Statistics:
Chihuahua: 158
miniature_poodle: 161
malamute: 208
beagle: 209
Pomeranian: 223
Dataset size: 899
Result saved to net\yolo\cfg/kong-tiny-yolov1.parsed
Dataset of 899 instance(s)
Traceback (most recent call last):
  File "flow", line 54, in <module>
    print('Enter training ...'); tfnet.train()
  File "D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\net\flow.py", line 37, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\net\yolo\data.py", line 146, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\net\yolo\data.py", line 69, in _batch
    img = self.preprocess(path, allobj)
  File "D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\net\yolo\test.py", line 97, in preprocess
    result = imcv2_affine_trans(im)
  File "D:\mywork\my_tensorflow\my_tensorflow\fine-tuning\thtrieu_yolo\utils\im_transform.py", line 19, in imcv2_affine_trans
    h, w, c = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

thanks in advance!

**Comment by imian00** [comment]
guys T.T i succeeded

**Comment by imian00** [comment]
for my bros who are experiencing same problems please watch #128
I'm not sure how could I solve my issues but
I think **AttributeError: 'NoneType' object has no attribute 'shape'** occurs when
1. you targeted wrong dataset path
2. your contents or format of the annotation xml files are not properly prepared.
especially be cautious for <folder> and <filename> tags. these two tags should be
written correctly

good luck!

**Comment by imian00** [comment]
한국어

**Comment by mpky** [comment]
> Solved it long time ago. Once you get this error, first make sure the number of annotation files and images are equal and Identical.

Shouldn't there be more annotation files than image files? Isn't one annotation file made per object in the image, rather than per image file?

**Comment by mpky** [comment]
> Solved it long time ago. Once you get this error, first make sure the number of annotation files and images are equal and Identical.

I actually don't think that matters as much as making sure there aren't any weird filetypes in the image data. cv2.imread will never throw an error so that's why this comes out once the shape is checked and there's not actually an image array in there.

**Comment by rjdbcm** [comment]
I had luck writing a check for matching annotation files of the same name and got rid of the <path> tag entirely from my annotation writer(causes issues with directory portability)

**Comment by mpky** [comment]
@rjdbcm what do you mean by path tag?
