### ISSUE TITLE
Type error when attempting to train

### ISSUE THREAD

**Issue by traw1234** [thtrieu/darkflow#161]
I've tried a variation of different commands and they all give the same error, the most generic sample being `python3 flow --model cfg/tiny-yolo-new.cfg --load bin/tiny-yolo-voc.weights --train` and I always get the error:

`WARNING:tensorflow:From /home/ubuntu/code/darkflow/net/yolov2/train.py:61: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
Traceback (most recent call last):
  File "flow", line 45, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/ubuntu/code/darkflow/net/build.py", line 63, in __init__
    self.setup_meta_ops()
  File "/home/ubuntu/code/darkflow/net/build.py", line 106, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "/home/ubuntu/code/darkflow/net/help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "/home/ubuntu/code/darkflow/net/yolov2/train.py", line 61, in loss
    coords = tf.concat([adjusted_coords_xy, adjusted_coords_wh], 3)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 117, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1406, in concat
    return concat_v2(values, concat_dim, name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1340, in concat_v2
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
`

Not really sure what the issue is but I don't think its the .cfg I made, same thing happens when I just use the default one. The issue seems to be when I add the --train flag, nothing changes when I add or remove any other flags.

**Comment by jcarletgo** [comment]
What version of tensorflow are you using? You should be using tensorflow 1.0+.

**Comment by traw1234** [comment]
The exact version is 1.0.0-alpha

**Comment by traw1234** [comment]
Was resolved by changing all instances of concat to concat_v2, I dunno if this is helpful or not.
