### ISSUE TITLE
Darkflow graph not being parsed correctly

### ISSUE THREAD

**Issue by ankghost0912** [thtrieu/darkflow#166]
Hi,

I'm trying to freeze the graph generated by `Darkflow` by using tensorflow's `freeze_graph` script. However, the script gives an error: `google.protobuf.text_format.ParseError: 2:1 : Expected identifier or number.`

I'm creating the graph file using the `--savepb` option as described in your `Readme`. To me this looks as if the graph was generated incorrectly. I wanted to know if that is indeed the case or I'm doing something wrong in generating the graph. 

Thanks.

**Comment by Momotyust** [comment]
Hi
Have you verified your graph created by "--savepb"? I am trying to do the same thing now, but it is easy for a beginner. 

I fine tuning tiny-yolo-voc and use "--savepb" option saved a .pb model, now I want to verify it. I use this code load a image:
`image=tf.gfile.FastGFile('a.jpg', 'rb').read()`
and then feed it to Session:
`with tf.Session(graph=graph) as sess:
            x = sess.graph.get_tensor_by_name('prefix/input:0')
            y = sess.graph.get_tensor_by_name('prefix/output:0')
            # Note: we didn't initialize/restore anything, everything is stored in the graph_def
            y_out = sess.run(y, {x:image})`
but it occured error when running it:
`Traceback (most recent call last):
  File "show_graph.py", line 63, in <module>
    y_out = sess.run(y, {x:image})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 786, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
`
I use the same way to verify a pb model which trained completely through tensorflow, it works fine.

Is there anyone has the same problem?

**Comment by thtrieu** [comment]
@ankghost0912 What do you mean by 

> To me this looks as if the graph was generated incorrectly

?
@Momotyust What is the error message? I only see the traceback.

**Comment by thtrieu** [comment]
@ankghost0912 What do you mean by 

> To me this looks as if the graph was generated incorrectly

? Please explain how the graph *looks* incorrect to you.

@Momotyust What is the error message? I only see the traceback.

**Comment by LucasMahieu** [comment]
I have the same problem, could some opne help me ? 
Input shape of the placeholder is not writen in the frozen pb graph
