### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: 

### ISSUE THREAD

**Issue by anonym24** [thtrieu/darkflow#180]
```
D:\files\TensorFlow\darkflow-master>python flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --savepb --verbalise=True
D:\files\TensorFlow\darkflow-master\dark\darknet.py:54: UserWarning: ./cfg/bin/yolo-voc.cfg not found, use cfg/yolo-voc.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/yolo-voc.cfg
Loading bin/yolo-voc.weights ...
Successfully identified 202704260 bytes
Finished in 0.025504589080810547s
Model has a VOC model name, loading VOC labels.

Building net ...
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 64)
 Load  |  Yep!  | local flatten 2x2                | (?, 13, 13, 256)
 Load  |  Yep!  | concat [27, 24]                  | (?, 13, 13, 1280)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 125)
-------+--------+----------------------------------+---------------
Running entirely on CPU
Finished in 11.38032579421997s

Rebuild a constant version ...
Model has a VOC model name, loading VOC labels.
Traceback (most recent call last):
  File "flow", line 61, in <module>
    tfnet.savepb(); exit('Done')
  File "D:\files\TensorFlow\darkflow-master\net\build.py", line 140, in savepb
    tf.train.write_graph(graph_def,'./',name,False)
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\framework\graph_io.py", line 69, in write_graph
    file_io.atomic_write_string_to_file(path, graph_def.SerializeToString())
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 352, in atomic_write_string_to_file
    write_string_to_file(temp_pathname, contents)
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 249, in write_string_to_file
    f.write(file_content)
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 90, in write
    self._prewrite_check()
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 82, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode), status)
  File "D:\files\Anaconda\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\files\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: ./graph-cfg/yolo-voc.pb.tmp886c2e3d68634d8e83087307044a6f0b : The system cannot find the path specified.


D:\files\TensorFlow\darkflow-master>pause
Press any key to continue . . .
```

Almost working ok with Windows, only have to fix this somehow.

I have actually successfully built .pb for tiny yolo  on windows when move .cfg and .weights (tiny-yolo-voc.cfg & tiny-yolo-voc.weights) just to "D:\files\TensorFlow\darkflow-master" (not to /bin and /cfg) it worked.

But for yolo2 (yolo-voc.cfg & yolo-voc.weights) it didn't work at all, I didn't get any  "Load  |  Yep! "
Then when I moved it to cfg and bin folder it's almost worked (at least I see  "Load  |  Yep! ") but get this error "Failed to create a NewWriteableFile" at end

**Comment by abagshaw** [comment]
Are you sure your `./graph-cfg/` folder exists? I get the same error if it doesn't exist. I'll be submitting a change soon that automatically creates the folder if it doesn't exist to avoid errors like this.

**Comment by thtrieu** [comment]
Close due to inactivity

**Comment by BanuSelinTosun** [comment]
Well, I am stuck at the same exact error as well. I know my file and folders do exists. What is wrong with this error, and is there a fix coming up?

**Comment by gloomyfish1998** [comment]
File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\training.py", line 929, in _export_eval_result
    is_the_final_export=is_the_final_export))
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\exporter.py", line 418, in export
    is_the_final_export)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\exporter.py", line 126, in export
    strip_default_attrs=self._strip_default_attrs)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 663, in export_savedmodel
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 716, in _export_saved_model_for_mode
    strip_default_attrs=strip_default_attrs)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 800, in _export_all_saved_models
    builder = saved_model_builder.SavedModelBuilder(temp_export_dir)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 92, in __init__
    file_io.recursive_create_dir(self._export_dir)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 379, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "C:\Program Files\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: D:/tensorflow/my_train/models/train\export\Servo\temp-b'153466596
9'; No such file or directory

D:\tensorflow\models\research>
==================================================================
when i end the train ,i got this issue, seems like tf did not create export/Servo directory for me
