### ISSUE TITLE
Master breaks loading yolo v2

### ISSUE THREAD

**Issue by blake-varden** [thtrieu/darkflow#187]
I pulled the yolo-v2 cfg/weights from the darkflow website.  Last week I ran the test
```
./flow --test test/ --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --gpu .9
```
and it was successful.  using https://github.com/thtrieu/darkflow/commit/40a7983b6134c5bfa5acbb6f8ccce358eae71164

I printed out the layer loading:
```
Loading bin/yolo-voc.weights ...
0 {'kernel': [3, 3, 3, 32], 'moving_variance': [32], 'biases': [32], 'gamma': [32], 'moving_mean': [32]}
1 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
2 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
3 {'kernel': [3, 3, 32, 64], 'moving_variance': [64], 'biases': [64], 'gamma': [64], 'moving_mean': [64]}
4 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
5 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
6 {'kernel': [3, 3, 64, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
7 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
8 {'kernel': [1, 1, 128, 64], 'moving_variance': [64], 'biases': [64], 'gamma': [64], 'moving_mean': [64]}
9 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
10 {'kernel': [3, 3, 64, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
11 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
12 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
13 {'kernel': [3, 3, 128, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
14 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
15 {'kernel': [1, 1, 256, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
16 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
17 {'kernel': [3, 3, 128, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
18 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
19 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
20 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
21 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
22 {'kernel': [1, 1, 512, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
23 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
24 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
25 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
26 {'kernel': [1, 1, 512, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
27 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
28 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
29 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
30 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
31 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
32 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
33 {'kernel': [1, 1, 1024, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
34 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
35 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
36 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
37 {'kernel': [1, 1, 1024, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
38 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
39 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
40 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
41 {'kernel': [3, 3, 1024, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
42 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
43 {'kernel': [3, 3, 1024, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
44 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
45 skipping because route not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
46 {'kernel': [1, 1, 512, 64], 'moving_variance': [64], 'biases': [64], 'gamma': [64], 'moving_mean': [64]}
47 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
48 skipping because reorg not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
49 skipping because route not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
50 {'kernel': [3, 3, 1280, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
51 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
52 {'kernel': [1, 1, 1024, 125], 'biases': [125]}
Successfully identified 202704260 bytes
```

This week I updated master and run the code and get an error reading in the weights:

```
./flow --test test/ --model mycfgs/yolo-voc.cfg --load bin/yolo-voc.weights --gpu .9
```

```
  File "./flow", line 3, in <module>
    from darkflow.net.build import TFNet
  File "./darkflow/net/build.py", line 46, in __init__
    darknet = Darknet(FLAGS)
  File "./darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "./darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "./darkflow/utils/loader.py", line 107, in create_loader
    return load_type(path, cfg)
  File "./darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "./darkflow/utils/loader.py", line 72, in load
    val = walker.walk(new.wsize[par])
  File "./darkflow/utils/loader.py", line 129, in walk
    'Over-read {}'.format(self.path)
AssertionError: Over-read jbox/bin/yolo-voc.weights
```
In comparing the two commits it seems as though in master more reorg/route layers get read in from the same config file.

```
Loading jbox/bin/yolo-voc.weights ...
0 {'kernel': [3, 3, 3, 32], 'moving_variance': [32], 'biases': [32], 'gamma': [32], 'moving_mean': [32]}
1 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
2 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
3 {'kernel': [3, 3, 32, 64], 'moving_variance': [64], 'biases': [64], 'gamma': [64], 'moving_mean': [64]}
4 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
5 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
6 {'kernel': [3, 3, 64, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
7 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
8 {'kernel': [1, 1, 128, 64], 'moving_variance': [64], 'biases': [64], 'gamma': [64], 'moving_mean': [64]}
9 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
10 {'kernel': [3, 3, 64, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
11 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
12 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
13 {'kernel': [3, 3, 128, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
14 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
15 {'kernel': [1, 1, 256, 128], 'moving_variance': [128], 'biases': [128], 'gamma': [128], 'moving_mean': [128]}
16 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
17 {'kernel': [3, 3, 128, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
18 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
19 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
20 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
21 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
22 {'kernel': [1, 1, 512, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
23 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
24 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
25 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
26 {'kernel': [1, 1, 512, 256], 'moving_variance': [256], 'biases': [256], 'gamma': [256], 'moving_mean': [256]}
27 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
28 {'kernel': [3, 3, 256, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
29 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
30 skipping because maxpool not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
31 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
32 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
33 {'kernel': [1, 1, 1024, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
34 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
35 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
36 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
37 {'kernel': [1, 1, 1024, 512], 'moving_variance': [512], 'biases': [512], 'gamma': [512], 'moving_mean': [512]}
38 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
39 {'kernel': [3, 3, 512, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
40 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
41 {'kernel': [3, 3, 1024, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
42 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
43 {'kernel': [3, 3, 1024, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}
44 skipping because leaky not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
45 skipping because route not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
46 skipping because reorg not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
47 skipping because route not in  ['convolutional', 'connected', 'local', 'select', 'conv-select', 'extract', 'conv-extract']
48 {'kernel': [3, 3, 3072, 1024], 'moving_variance': [1024], 'biases': [1024], 'gamma': [1024], 'moving_mean': [1024]}


Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)

```

**Comment by blake-varden** [comment]
never mind it looks like the cfg files i was using are different

**Comment by blake-varden** [comment]
Nevermind, it turns out that the options to the flow script doesnt handle model files not located in the config bin well.  I needed to specify the config directory.

```
./flow --test test/ --config mycfgs/ --model mycfgs/yolo-voc.cfg --load bin/yolo-voc.weights --gpu .9
```

**Comment by dgorissen** [comment]
I still get this problem with latest master using yolo-voc.weights as downloaded from the yolo site. Adding the config flag makes no difference.

**Comment by yanmenglu** [comment]
@blake-varden @dgorissen ,I met the same problem. could you sovle it with the  latest clean master?

**Comment by junxuezheng** [comment]
@blake-varden @yanmenglu @dgorissen 
i download the yolo-voc.weights from yolo website,it says AssertionError Over-read bin/yolo-voc.weights.
where could i get the right yolo-voc.weights?
