### ISSUE TITLE
Error in camera 

### ISSUE THREAD

**Issue by moh3th1** [thtrieu/darkflow#19]
I am trying to use the camera demo and I got this error 
```
Running entirely on CPU
Finished in 1.87715506554s

Press [ESC] to quit demo
Traceback (most recent call last):
  File "./flow", line 49, in <module>
    tfnet.camera(FLAGS.demo)
  File "/home/moh/Downloads/darkflow/net/help.py", line 78, in camera
    })[0], frame, False))
  File "/home/moh/Downloads/darkflow/net/yolo/test.py", line 106, in postprocess
    if max_prob > _thresh[label]:
KeyError: 'aeroplane'
```
![screenshot from 2016-12-23 21-26-15](https://cloud.githubusercontent.com/assets/15180702/21461058/bb8ecca4-c956-11e6-84fc-70417a30b8c9.png)

**Comment by thtrieu** [comment]
Sorry that was an experiment of mine. Please update the new commit.

**Comment by moh3th1** [comment]
It worked.
Thanks
