### ISSUE TITLE
Slow prediction time

### ISSUE THREAD

**Issue by Mo7amedSala7Nazir** [thtrieu/darkflow#212]
When I used called `result = tfnet.return_predict(imgcv)` and calculated the time it took in this command.
I found that it took 0.85 seconds which is not so real time.

So, If there is anything that could be causing this slowdown in performance, from where can I dig into it and know it.

My environment is a GeForce GTX 1080.

Thank you @thtrieu so much for this support.

**Comment by Dhruv-Mohan** [comment]
Hmm that's definitely odd yolov2 should process an image in 40ms  @Mo7amedSala7Nazir what cfg file are you using? Also, what's the image size?

Lets also scope the performance further, can you find the forward pass time and the pre-processing time?

**Comment by Mo7amedSala7Nazir** [comment]
@Dhruv-Mohan first of all thanks for the quick reply.

The image size is 1920x1200 (Udacity self driving car dataset). But I also tried it on the Dog image and produced the same time.
The cfg file is `cfg/yolo.cfg` and the weights file I got from the link in the readme file.

So I think these are concerning YOLO v2.

**Comment by Dhruv-Mohan** [comment]
@Mo7amedSala7Nazir  Alright, lets scope the program time further.   Can you check the time it takes to do the [Forward Pass](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/flow.py#L77) and [Post Processing](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolov2/test.py#L23) ?

**Comment by Mo7amedSala7Nazir** [comment]
@Dhruv-Mohan I did what you said and the forward pass seemed to be the one delaying it, with **0.755 seconds** where the post processing is **0.0015 seconds** 
What do you want me to do next ?

**Comment by abagshaw** [comment]
Just checking, you did set `"gpu": 1.0` in your options right?

**Comment by Mo7amedSala7Nazir** [comment]
No I was not, but when running it in the shell tensorflow states that it is using the GPU,

**however** when I added it now it displayed the following error:
`E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
Traceback (most recent call last):
  File "salahDarkflow.py", line 8, in <module>
    tfnet = TFNet(options)
  File "/home/carkyo1080-2/Desktop/Salah/darkflow-master/darkflow/net/build.py", line 71, in __init__
    self.setup_meta_ops()
  File "/home/carkyo1080-2/Desktop/Salah/darkflow-master/darkflow/net/build.py", line 120, in setup_meta_ops
    self.sess = tf.Session(config = tf.ConfigProto(**cfg))
  File "/home/carkyo1080-2/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1186, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/carkyo1080-2/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 551, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/carkyo1080-2/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.`

**Comment by Mo7amedSala7Nazir** [comment]
Ok so now It told me that it wanted to allocate 7.92GiB but there was only 7.37 GiB free memory.

@Dhruv-Mohan and @abagshaw can you tell me how can I lower the size of allocated objects (Tensors).
I am afraid this may require some source code modifications.

And again, Thanks so much for your help

**Comment by abagshaw** [comment]
@Mo7amedSala7Nazir Yup set it to `"gpu": 0.8` to allocate 80% of your total GPU memory (or whatever fraction you want).

**Comment by Dhruv-Mohan** [comment]
Nice! looks like you've fixed it

**Comment by Mo7amedSala7Nazir** [comment]
@abagshaw It worked however the performance was slightly better from 0.85 to 0.76 seconds on `"gpu": 0.8` So what do other tricks you think can enhance this ?

**Comment by Dhruv-Mohan** [comment]
Did you get a similar time on the Dog image aswell?

**Comment by Mo7amedSala7Nazir** [comment]
Unfortunately, Yes

This is a full description on my environment:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8225
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.36GiB

**Comment by Dhruv-Mohan** [comment]
@Mo7amedSala7Nazir  Sorry, I'm stumped now. Can you try logging the gpu usage when you run the network?  Maybe that'll give us some clues.

**Comment by Mo7amedSala7Nazir** [comment]
@Dhruv-Mohan How can I do so ? I am sorry for these questions but I am new to tensorflow and this is the first time for me to train this amount of Data on a GPU

**Comment by Mo7amedSala7Nazir** [comment]
BTW, I changed only one line of code that should not make a difference, in file simple.py line 17,
from
`self.out = tf.concat(routes_out, 3)`
to
`self.out = tf.concat(3, routes_out)`

because it gave me an error

**Comment by abagshaw** [comment]
Oh you are probably not running the latest version of tensorflow. Can you check to make sure you are running the latest version of `tensorflow-gpu` with `pip install tensorflow-gpu --upgrade`

**Comment by Mo7amedSala7Nazir** [comment]
@abagshaw It is upgrading now, I do not think that can make a difference in the performance, can it ?

**Comment by abagshaw** [comment]
No I don't, unless for some reason you were using `tensorflow` instead of `tensorflow-gpu` :) but I don't think that's the case.

**Comment by Dhruv-Mohan** [comment]
@Mo7amedSala7Nazir  if you're on linux then you can use nvidia-smi to get relevant gpu information of that instant

**Comment by Mo7amedSala7Nazir** [comment]
@abagshaw The upgrading increased the performance a bit it became 0.67 sec

@Dhruv-Mohan I typed nvidia-smi in the shell, but I do not know how to use it ? Can you direct me to a tutorial or sth that says how to monitor the GPU usage

**Comment by Dhruv-Mohan** [comment]
This should help [Gpu stat logging](https://unix.stackexchange.com/questions/252590/how-to-log-gpu-load/252591)

**Comment by OmarMAmin** [comment]
I'm having the same problem as @Mo7amedSala7Nazir  , using 1080 GTX and each image takes around 0.4 seconds, not 0.8 as Mohamed but I'm working on two GPUs, I can't make sure if on test time darkflow is utilizing both, I think this is done only in the training,

**Comment by Mo7amedSala7Nazir** [comment]
@abagshaw @Dhruv-Mohan I am currently using python 2.7 not 3.5 so does that make a difference ? since I compiled the Cython modules using `python` not `python3` command.

@OmarMAmin What version of python did you compile it with and what version are you cuurently using ?

**Comment by Dhruv-Mohan** [comment]
@Mo7amedSala7Nazir  That shouldn't make a difference and if it did it would reflect on the post processing time. On a titan x the forward pass for yolov2 usually takes 30ms give or take.

**Comment by Mo7amedSala7Nazir** [comment]
Ok @Dhruv-Mohan , so maybe I missed something.....

Can you outline to me the steps from cloning the repo, until getting an output. I am really having a hard time figuring out what is going on, so I will redo the whole thing again.

Thanks in advance

**Comment by ydzhang12345** [comment]
I am having the same problem. I am also using gtx1080, and inference for a single figure is 0.8s for  yolo2.

**Comment by mursalal** [comment]
Is it ok?
....
`step 39 - loss nan - moving ave loss nan`
`step 40 - loss nan - moving ave loss nan`
`step 41 - loss nan - moving ave loss nan`
`step 42 - loss nan - moving ave loss nan`

.... etс

**Comment by 87216LiaoXin** [comment]
What's  up?

2017-05-28 23:29 GMT+08:00 Alihan <notifications@github.com>:

**Comment by mursalal** [comment]
@87216LiaoXin I figured it out it. Thank you.

**Comment by ydzhang12345** [comment]
@mursalal can you give some hints why the processing time is long?

**Comment by feber** [comment]
Thank you @abagshaw i miss that one. Put `"gpu": 0.8` in options make it work as expected.
