### ISSUE TITLE
Fails to generate checkpoint

### ISSUE THREAD

**Issue by EmmanouelP** [thtrieu/darkflow#224]
So i am on Windows and i use the following commad to  make some training:

python ./flow --train --model cfg/tiny-yolo-new.cfg --dataset C:\Users\manolis\VOC\JPEGImages --epoch 300 --annotation C:\Users\manolis\VOC\Annotations --gpu 0.8

At the end of my training i get the following error:

Traceback (most recent call last):
  File "./flow", line 56, in <module>
    print('Enter training ...'); tfnet.train()
  File "C:\Users\manolis\darkflow\darkflow\net\flow.py", line 67, in train
    if ckpt: _save_ckpt(self, *args)
  File "C:\Users\manolis\darkflow\darkflow\net\flow.py", line 21, in _save_ckpt
    with open(profile, 'wb') as profile_ckpt:
FileNotFoundError: [Errno 2] No such file or directory: './ckpt/cfg/tiny-yolo-new-10.profile'

Any insight on that?

**Comment by 4F2E4A2E** [comment]
I am also very interested the answer for this question.

**Comment by 4F2E4A2E** [comment]
So, now i really need your help. I am trying to train a 'dog' set with only 3 images and it is taking hours and still not completing it. I am running this **cmd**:
```
./flow --model cfg/yolo-new.cfg --dataset VOCdevkit/VOC2007_custom/JPEGImages_custom/ --annotation VOCdevkit/VOC2007_custom/Annotations_custom/ --train --backup /c/darkflow/ckpt/
```
**Error**:
```
step 664 - loss 98.2300796508789 - moving ave loss 98.41901069004946
Finish 664 epoch(es)
step 665 - loss 98.30776977539062 - moving ave loss 98.40788659858357
Finish 665 epoch(es)
step 666 - loss 98.3103256225586 - moving ave loss 98.39813050098107
Traceback (most recent call last):
  File "./flow", line 66, in <module>
    tfnet.train()
  File "C:\darkflow\darkflow\net\flow.py", line 65, in train
    if not ckpt: _save_ckpt(self, *args)
  File "C:\darkflow\darkflow\net\flow.py", line 21, in _save_ckpt
    with open(profile, 'wb') as profile_ckpt:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/darkflow/ckpt/cfg/yolo-new-666.profile'
2017-05-15 18:14:44.889107: E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\events_writer.cc:162] The events file ./summary/train\events.out.tfevents.1494864883.pc has disappeared.
2017-05-15 18:14:44.889199: E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\events_writer.cc:131] Failed to flush 1 events to ./summary/train\events.out.tfevents.1494864883.pc
```

Please help, all I am trying is to train my own model.

**Comment by beebrain** [comment]
Do you have ckpt/cfg in your project? If not make that folder.

**Comment by EmmanouelP** [comment]
@beebrain Thanks man this seemd to have solved the issue hence closing this issue
