### ISSUE TITLE
I have some ImportError:No module named contrib.slim

### ISSUE THREAD

**Issue by ma3252788** [thtrieu/darkflow#294]
mcj@ubuntu:~/darkflow$ ./flow --model cfg/yolo-new.cfg
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/mcj/darkflow/darkflow/cli.py", line 3, in <module>
    from darkflow.net.build import TFNet
  File "/home/mcj/darkflow/darkflow/net/build.py", line 5, in <module>
    from .ops import op_create, identity
  File "/home/mcj/darkflow/darkflow/net/ops/__init__.py", line 1, in <module>
    from .simple import *
  File "/home/mcj/darkflow/darkflow/net/ops/simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named contrib.slim

**Comment by abagshaw** [comment]
Can you try uninstalling tensorflow and re-installing using `pip` as it appears the issue is finding a module that's part of the tensorflow library.

**Comment by ma3252788** [comment]
Thanks a lot ,I will try it as you say.

**Comment by stAyushJain** [comment]
@ma3252788 any success ? I got the same issue
