### ISSUE TITLE
OOM errors when training.

### ISSUE THREAD

**Issue by jubjamie** [thtrieu/darkflow#296]
All of a sudden I have been unable to train because i'm getting Out Of Memory Errors. I am using GPU and have tried reducing the GPU fraction but it doesn't work. I've not had a problem with training until now. Now, for whatever reason, i'm just unable to train because I run out of memory immediately. My card is a K40 with 12Gb of memory and it's been fine before. Nothing has changed that I am aware of.

**Comment by dimaxano** [comment]
What is "subdivision" value in your cfg file?

**Comment by jubjamie** [comment]
Whatever the default is. For the voc config which I was retraining on it says 1 with 8 commented out. I set the batch from 16 to 8 (with --batch 8) and now it's working but that seems like a very small batch size. Seems to be very 50/50 if it will work. I've seen people with much smaller cards manage fine.

```
[net]
# Testing
batch=1
subdivisions=1
# Training
# batch=64
# subdivisions=8
width=608
height=608
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
```

**Comment by dimaxano** [comment]
Try to increase subdivision till 16 and try to set necessary for you batch size

**Comment by jubjamie** [comment]
I currently have it training at the moment but will try that later. Thanks.

**Comment by borasy** [comment]
i met the same problem #241 . to train on a bigger batch size you need to use the old .cfg which has (416x416) instead of the new .cfg with (608x608) resolution.

**Comment by jubjamie** [comment]
@borasy Hmm ok i've just read through those issues. Interesting. I'm confused as to why it was fine before but now it isn't. Anyway, where can I find the old cfg? Thanks.

**Comment by borasy** [comment]
there's nothing different between the old and the new cfg except the resolution. so just change it to 416x416 and you're good to go.

**Comment by uwmyuan** [comment]
@borasy  I have similar problem #241 . But when using `--gpu 0.0`, everything is fine. Any other value would lead to an OOM error. I tried your findings about the `cfg`, it didn't work for me.

**Comment by linydf** [comment]
@uwmyuan when using -- gpu 0.0 .it come this error
step 44 - loss 106.16590118408203 - moving ave loss 109.05830211698984
step 45 - loss 107.10467529296875 - moving ave loss 108.86293943458773
step 46 - loss 108.22335815429688 - moving ave loss 108.79898130655866
step 47 - loss 106.01653289794922 - moving ave loss 108.52073646569772
step 48 - loss 106.04692077636719 - moving ave loss 108.27335489676469
step 49 - loss 107.21436309814453 - moving ave loss 108.16745571690267
step 50 - loss 109.32177734375 - moving ave loss 108.2828878795874
step 51 - loss 112.48167419433594 - moving ave loss 108.70276651106226
step 52 - loss 107.1461410522461 - moving ave loss 108.54710396518065
step 53 - loss 107.17160034179688 - moving ave loss 108.40955360284228
step 54 - loss 107.15045166015625 - moving ave loss 108.28364340857368
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "E:\darkflow-master\darkflow\cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "E:\darkflow-master\darkflow\net\flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "E:\darkflow-master\darkflow\net\yolo\data.py", line 135, in shuffle
    x_batch = np.concatenate(x_batch, 0)
ValueError: need at least one array to concatenate
if you ever happen???
