### ISSUE TITLE
build  own .bp, but predict nothing

### ISSUE THREAD

**Issue by zhyj3038** [thtrieu/darkflow#297]
very much thanks for your great work!

after I download original pascal VOC "tiny-yolo-voc.cfg" and "tiny-yolo-voc.weights", and build the pb with 
"flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --savepb",
 then predict sample_images with 
"flow --pbLoad savepb/tiny-yolo-voc.pb --metaLoad savepb/tiny-yolo-voc.meta --imgdir sample_img/ "  , 
everything is right;

but aftera train my own dog dataset ,   I build pb with 
"flow --model "cfg/tiny-yolo-voc-1c.cfg"  --backup "/my_path/ckpt/" --load -1  --savepb", 
it build a .pb file,  and at the same time correctly predict sample_image . now I predict images with 
"flow --pbLoad "savepb/tiny-yolo-voc-1c.pb" --metaLoad "savepb/tiny-yolo-voc-1c.meta" --imgdir "sample_img/" ,
I get no boxes;

I can not think where is wrong? maybe it cannote build a pb from checkpoint??  help  and thanks!!

**Comment by abagshaw** [comment]
Can you try setting a custom threshold like `--threshold 0.4` and see if that does anything when trying to generate predictions using the built `.pb`

**Comment by zhyj3038** [comment]
no, I have tried,  even --threshold 0 cannot work. It seems strange because others meet this problem .

**Comment by abagshaw** [comment]
Can you try to generate predictions directly from your trained data using:
`flow --model "cfg/tiny-yolo-voc-1c.cfg" --backup "/my_path/ckpt/" --load -1 --imgdir "sample_img/"`

If that doesn't work then something is wrong with your trained model (not with how the `.pb` is being built)

**Comment by zhyj3038** [comment]
@abagshaw   I get you .   your script can work , it will detection the right object,  as I mentiond above.   so I wonder if th .pb is the trouble.

**Comment by abagshaw** [comment]
Whoops, sorry I missed that 😄. Could you post a link (or paste in) the contents of `tiny-yolo-voc-1c.meta` so I can have a look at that?

**Comment by zhyj3038** [comment]
ok, if possible, I can even send you the whole project to your emal.  I now am afraid of building .pb, because I failed to build it it my classification task either.....><

content of meta:
{"labels": ["penguin"], "jitter": 0.2, "anchors": [1.08, 1.19, 3.42, 4.41, 6.63, 11.38, 9.42, 5.11, 16.62, 10.52], "random": 1, "colors": [[254, 254, 254]], "num": 5, "thresh": 0.5, "inp_size": [416, 416, 3], "bias_match": 1, "out_size": [13, 13, 30], "model": "./cfg/tiny-yolo-voc-1c.cfg", "absolute": 1, "name": "tiny-yolo-voc-1c", "coord_scale": 1, "rescore": 1, "class_scale": 1, "noobject_scale": 1, "object_scale": 5, "classes": 1, "coords": 4, "softmax": 1, "net": {"hue": 0.1, "saturation": 1.5, "angle": 0, "decay": 0.0005, "learning_rate": 0.001, "scales": ".1,10,.1,.1", "batch": 64, "height": 416, "channels": 3, "width": 416, "subdivisions": 8, "steps": "-1,100,20000,30000", "policy": "steps", "max_batches": 40100, "type": "[net]", "momentum": 0.9, "exposure": 1.5}, "type": "[region]"}

**Comment by zhyj3038** [comment]
I wonder maybe my usage is wrong?  or we can built .pb from .wight correctly, but can not from ckpt?

**Comment by abagshaw** [comment]
@zhyj3038 Hmm, wish I could be of more help here, but nothing looks out of the ordinary there at first glance. If `flow --model "cfg/tiny-yolo-voc-1c.cfg" --backup "/my_path/ckpt/" --load -1 --imgdir "sample_img/"` does indeed generate the expected predictions then either there is a problem with the generated `.pb` or something isn't getting put into/loaded from the `.meta` that should be.

When I designed the system to load from `.pb` and `.meta` files into darkflow for predictions I didn't test it with trained checkpoints (only pretrained `.weights`) so most likely there is some attribute or piece of information getting lost along the way. Unfortunately I won't have time to look into this further for another week - someone else might or if not I'll get back to it when I have more time.

**Comment by zhyj3038** [comment]
@abagshaw  all  right, thank you very much !   the predict process with pb is right, so I  think the problem is it can not built pb with ckpt.

**Comment by zhyj3038** [comment]
now I get the .pb which can generate correct boxes, with  model  initilized with pretrain .weight.  I will explore if .pb built from ckpt can work.  In fact ,several days before I initilize with .weight and it work. but I forgot until your tips. very thanks to you !!

**Comment by zhyj3038** [comment]
I'm very sorry, it is my fault.  the code work well, and can generate correct .pb from .ckpt.  perhaps I have modifyied somthing before  and lead the bad result.

**Comment by cdragon2** [comment]
i have same problem with u ..

how can make correct .pb file form ckpt?

help T.T

**Comment by sharoseali** [comment]
After a long time spend on training  i got .meta , .index and .profile  file in ckpt folder  ... and i am getting this error even specifying the correct file path  @abagshaw . zhyj3038 or any one help me please ...?

[Command: python -u C:\Users\dell\Desktop\darkflow-master\Realtimevideo]
C:\Users\dell\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Parsing C:/Users/dell/Desktop/darkflow-master/cfg/tiny-yolo-voc-1c.cfg
Loading None ...
Finished in 0.0s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 30)
-------+--------+----------------------------------+---------------
2018-05-22 22:36:43.806873: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
GPU mode with 1.0 usage
2018-05-22 22:36:43.866087: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
name: NVS 5200M major: 2 minor: 1 memoryClockRate(GHz): 1.344
pciBusID: 0000:01:00.0
totalMemory: 1.00GiB freeMemory: 822.90MiB
2018-05-22 22:36:43.866784: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1093] Ignoring visible gpu device (device: 0, name: NVS 5200M, pci bus id: 0000:01:00.0, compute capability: 2.1) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
Loading from ./ckpt/tiny-yolo-voc-1c-168498
2018-05-22 22:36:45.824736: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.824819: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.824875: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.824940: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.825722: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.826339: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.827011: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.827579: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.828257: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.828796: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.829338: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.829863: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.830665: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.831160: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.831706: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.832226: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.832756: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.833253: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.833824: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.834457: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.835139: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.835637: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.836328: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.836943: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.841579: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.842065: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.842692: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.843249: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.843824: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.844398: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.845027: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.845600: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.846228: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.846796: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.847423: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.847962: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.848591: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.849109: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.849734: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.850301: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.850907: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.851433: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.
; No such process
2018-05-22 22:36:45.853956: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1093] Ignoring visible gpu device (device: 0, name: NVS 5200M, pci bus id: 0000:01:00.0, compute capability: 2.1) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.

; No such process
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\help.py", line 33, in load_from_ckpt
    try: self.saver.restore(self.sess, load_point)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.

; No such process
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

Caused by op 'save/RestoreV2_1', defined at:
  File "C:\Users\dell\Desktop\darkflow-master\Realtimevideo", line 12, in <module>
    tfnet = TFNet(options)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\build.py", line 76, in __init__
    self.setup_meta_ops()
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\build.py", line 150, in setup_meta_ops
    max_to_keep = self.FLAGS.keep)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1218, in __init__
    self.build()
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1020, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./ckpt/tiny-yolo-voc-1c-168498: Not found: FindFirstFile failed for: ./ckpt : The system cannot find the path specified.

; No such process
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\darkflow-master\Realtimevideo", line 12, in <module>
    tfnet = TFNet(options)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\build.py", line 76, in __init__
    self.setup_meta_ops()
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\build.py", line 151, in setup_meta_ops
    if self.FLAGS.load != 0: self.load_from_ckpt()
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\help.py", line 34, in load_from_ckpt
    except: load_old_graph(self, load_point)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\net\help.py", line 45, in load_old_graph
    ckpt_loader = create_loader(ckpt)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\utils\loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\utils\loader.py", line 19, in __init__
    self.load(*args)
  File "C:\Users\dell\Desktop\darkflow-master\darkflow\utils\loader.py", line 89, in load
    saver = tf.train.import_meta_graph(meta)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1803, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 555, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File ./ckpt/tiny-yolo-voc-1c-168498.meta does not exist.
[Finished in 8.038s]

**Comment by zhyj3038** [comment]
I'm sorry. I have not focus on darkflow for a long time, so can not help you. @sharoseali

**Comment by amankumarjain** [comment]
> I'm very sorry, it is my fault. the code work well, and can generate correct .pb from .ckpt. perhaps I have modifyied somthing before and lead the bad result.

is .pb working without pretrained weight also?
how you solved it, please help
