### ISSUE TITLE
translate  .weights to .pb

### ISSUE THREAD

**Issue by LiangHao92** [thtrieu/darkflow#352]
when I tried to translate .weight to .pb, the error occurs:

Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/darkflow/cli.py", line 35, in cliHandler
    tfnet.savepb(); exit('Done')
  File "/usr/local/lib/python2.7/dist-packages/darkflow/net/build.py", line 171, in savepb
    os.makedirs(os.path.dirname(name), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

How can I deal with it

**Comment by LiangHao92** [comment]
I figure it out . because my python is 2.7

**Comment by LiangHao92** [comment]
2.7 is available.replace 
os.makedirs(os.path.dirname(name), exist_ok=True)
with
os.makedirs(os.path.dirname(name), 0777)is  ok

**Comment by abhishekkumardwivedi** [comment]
Did face this issue and above solution worked for me.
