### ISSUE TITLE
how to extract and save all layers weights except the last detection layer?

### ISSUE THREAD

**Issue by miltonbd** [thtrieu/darkflow#37]

**Comment by thtrieu** [comment]
Do you want to save it as a `.pb` or `.weights`?

**Comment by miltonbd** [comment]
hithanks for your awesome work. my problem i have to detect 128 classes of objects. for this reason i just need to change last detection layer and this detection weight should be randomy initlialized as it does not present in the pretrained weights. except the last detection layer all weights should be initialized from pretrained weights.
that's why i need to extract each layer weight separately say: {'conv1_1':'conv1_1.weights',......}


thanks
Regardsmilton 

    On Tuesday, January 24, 2017 6:28 PM, Trieu <notifications@github.com> wrote:
 

 Do you want to save it as a .pb or .weights?—

**Comment by thtrieu** [comment]
I got your idea. The only thing you have to do is to design another config file `.cfg` with all except the last layer being identical to the original config. 

For example, suppose you want to reuse all layers except the last one from `A.cfg` to `B.cfg`. Make sure the first (N-1) layers of A and B are identical, then run 

```
./flow --model cfg/B.cfg --load bin/A.weights
```
 Will achieve your goal.

**Comment by miltonbd** [comment]
hi 
i got this eeror: cfg_path, FLAGS.model))
Parsing cfg/v1.1/traffic.cfg
Loading bin/v1.1/yolo-coco.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/media/milton/Research1/research-projects/YOLO/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/media/milton/Research1/research-projects/YOLO/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/media/milton/Research1/research-projects/YOLO/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/media/milton/Research1/research-projects/YOLO/darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "/media/milton/Research1/research-projects/YOLO/darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "/media/milton/Research1/research-projects/YOLO/darkflow/utils/loader.py", line 69, in load
    val = walker.walk(new.wsize[par])
  File "/media/milton/Research1/research-projects/YOLO/darkflow/utils/loader.py", line 131, in walk
    dtype='({})float32,'.format(size)
  File "/usr/lib/python2.7/dist-packages/numpy/core/memmap.py", line 260, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size

i think it is due fact that the network model has more parameters than the actual paramater provided in weights. making class less than 80 works without any error.
thanks
Regardsmilton 

    On Tuesday, January 24, 2017 9:48 PM, Trieu <notifications@github.com> wrote:
 

 I got your idea. The only thing you have to do is to design another config file .cfg with all except the last layer being identical to the original config.For example, suppose you want to reuse all layers except the last one from A.cfg to B.cfg. Make sure the first (N-1) layers of A and B are identical, then run./flow --model cfg/B.cfg --load bin/A.weights
Will achieve your goal.—

**Comment by thtrieu** [comment]
Please send me the two configs file and the command you used that lead to this error.

**Comment by miltonbd** [comment]
hi
print os.system('./flow --model cfg/v1.1/traffic.cfg --load bin/v1.1/yolo-coco.weights') 
coco.name should be 128 rows for traffic.cfg

regardsmilton


 

    On Tuesday, January 24, 2017 10:28 PM, Trieu <notifications@github.com> wrote:
 

 Please send me the two configs file and the command you used that lead to this error.—
