### ISSUE TITLE
Can not use

### ISSUE THREAD

**Issue by jinfagang** [thtrieu/darkflow#379]
```
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/Volumes/xs/CodeSpace/ng/ai/frameworks/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/Volumes/xs/CodeSpace/ng/ai/frameworks/darkflow/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

Apparently, I installed tensorflow in both Python2.7 and Python3.6, this is really not resonable that cannot found tensorflow.....

**Comment by jubjamie** [comment]
This is 99.9999% an issue with how you've installed Tensorflow and not darkflow itself. Ensure that if you are using an environment that you have correctly entered it, especially important in IDEs.

**Comment by jinfagang** [comment]
Yeah, I figured it out finally, many thanks.

**Comment by sirShakir** [comment]
Im a getting this same error. How did you resolve?
