### ISSUE TITLE
AssertionError with four byte size difference when converting

### ISSUE THREAD

**Issue by sunsided** [thtrieu/darkflow#421]
I'm getting a rather weird error trying to convert a `darknet` trained (adjusted) Tiny YOLO model with `flow --savepb` where it complains about having an unexpected file size; the size difference appears to be exactly four bytes though:

```python
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/mmayer/dev/ml/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/mmayer/dev/ml/darkflow/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/home/mmayer/dev/ml/darkflow/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/mmayer/dev/ml/darkflow/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/mmayer/dev/ml/darkflow/darkflow/utils/loader.py", line 108, in create_loader
    return load_type(path, cfg)
  File "/home/mmayer/dev/ml/darkflow/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/mmayer/dev/ml/darkflow/darkflow/utils/loader.py", line 80, in load
    walker.offset, walker.size)
AssertionError: expect 63184556 bytes, found 63184560
```

I was trying it with different versions of TensorFlow, specifically 1.0.1 and 1.3.1, but that didn't change anything.
Does anyone have an idea what could trigger this issue?

**Comment by sunsided** [comment]
[This comment](https://github.com/thtrieu/darkflow/issues/107#issuecomment-289999490) on #107 suggests that training from scratch might solve this issue. I retrained the network using `darknet` an converted it again, but do still receive the same error.

**Comment by sunsided** [comment]
[This comment](https://github.com/Cuky88/3D-BoundingBox/issues/13#issue-256509502) suggests to change `self.offset = 16` to `self.offset = 20` in `utils/loader.py`'s `weights_walker.__init__()` method. If I do that the error disappears but I have no idea if that is a smart thing to do.

**Comment by QueenJuliaZxx** [comment]
I meet this problems too,I think it is caused by the unpair between .weight and .cfg , maybe it is a little cue, but I have no idea to solve it,so sorry

**Comment by shangliy** [comment]
Modify **loader.py** under darkflow/utils may help.
Change the line 121 from self.offset = 16 to self.offset = 20~~~
This work for me, hope help~

**Comment by QueenJuliaZxx** [comment]
thank you for your help，i have solve it ，thankyou again

发自我的 iPhone

**Comment by yw455801125** [comment]
i have Changed the line 121 from self.offset = 16 to self.offset = 20! but the same error not disappear!

**Comment by yw455801125** [comment]
why should we change this number "self.offset" value

**Comment by ttorkar** [comment]
My guess is that the offset that deals with the difference between c and python but I could be wrong. Can you try reduce the offset to 12 to keep the expected bytes equal to the actual bytes. Let me know how that goes.

**Comment by yw455801125** [comment]
This is my training output used darkflow, please tell me, what is the format of the file, why not get the .CKPT format file! How can I generate the required weight file for tensorflow?(.ckpt)
![image](https://user-images.githubusercontent.com/26087367/34610551-9b8ded06-f25c-11e7-995c-3d1118db2852.png)

**Comment by ttorkar** [comment]
@yw455801125 how did you get it working? You can convert it by using --savepb or something similar. It is in the Readme.

**Comment by shangliy** [comment]
@yw455801125  The weights I used to transform are from Darknet not darkflow. The weights storage format from Darkflow and Darknet are different. So, I guess my solution may not work on your case.

**Comment by nicolefinnie** [comment]
I think it's because the size of the header of the most up-to-date yolo v2 weights changed from 16 bytes to 20 bytes, so the `weights_walker` doesn't reach the end of the file because it expects an older header size.

**Comment by fbadaud** [comment]
@yw455801125  in case you have not solved this issue yet or for others , you need to upgrade your darkflow installation after your modification of darkflow/utils/loader.py 
you can use: pip install . --upgrade

**Comment by HsGaurav** [comment]
go the same error 
AssertionError: labels.txt and ../darknet/cfg/yolov2-tiny.cfg indicate inconsistent class numbers
please someone have any answer REPLY

**Comment by fbadaud** [comment]
@HsGaurav 
to fix error in labels i just link the labels.txt  to the corresponding file with list of label used on the dataset on which the network as been trained.
for example for yolov2-voc I linked to darknet/data/voc.names 
etc...

**Comment by chesnaught7** [comment]
how do you link a file @fbadaud

**Comment by DigvijaySingh7720** [comment]
Error :- AssertionError: expect 63184556 bytes, found 63184560

Solution : " ./darkflow/utils/loader.py" at  line 121, you will find self.offset= 16 or 20.
update to be done : - found 63184560 - expect 63184556 = 4, then add 4 to self.offset = add this 4 (or any other value) diff to 16 or 20 and then run your command again.

Best of Luck, it work for me, hope it may work for you as well, keep helping other.
