### ISSUE TITLE
Training our own data

### ISSUE THREAD

**Issue by normansiboro** [thtrieu/darkflow#439]
I got this error when I was training my data set. I already followed every step 

Enter training ...

cfg/tiny-yolo-voc-1c.cfg parsing train/Annotations
Parsing for ['macncheese']
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\MDPSystemSupport\OJT II\Python Project\Tensorflow\darkflow\darkflow\cli.py", line 29, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "D:\MDPSystemSupport\OJT II\Python Project\Tensorflow\darkflow\darkflow\net\flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "D:\MDPSystemSupport\OJT II\Python Project\Tensorflow\darkflow\darkflow\net\yolo\data.py", line 97, in shuffle
    data = self.parse()
  File "D:\MDPSystemSupport\OJT II\Python Project\Tensorflow\darkflow\darkflow\net\yolo\data.py", line 18, in parse
    dumps = pascal_voc_clean_xml(ann, meta['labels'], exclusive)
  File "D:\MDPSystemSupport\OJT II\Python Project\Tensorflow\darkflow\darkflow\utils\pascal_voc_clean_xml.py", line 22, in pascal_voc_clean_xml
    annotations = glob.glob(str(annotations)+'*.xml')
  File "C:\Python35\lib\glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "C:\Python35\lib\glob.py", line 54, in _iglob
    yield from glob1(dirname, basename)
  File "C:\Python35\lib\glob.py", line 90, in glob1
    return fnmatch.filter(names, pattern)
  File "C:\Python35\lib\fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "C:\Python35\lib\fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "C:\Python35\lib\re.py", line 224, in compile
    return _compile(pattern, flags)
  File "C:\Python35\lib\re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python35\lib\sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python35\lib\sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "C:\Python35\lib\sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "C:\Python35\lib\sre_parse.py", line 575, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range i-a at position 179

I use [https://github.com/tzutalin/labelImg](url) to label my images
I want to train my data only for one class

**Comment by normansiboro** [comment]
I have fixed this by changing 
`annotations = glob.glob(str(annotations)+'*.xml') to annotations = glob.glob('*.xml') in the darkflow\utils\pascal_voc_clean_xml.py`
as noted at [https://github.com/thtrieu/darkflow/issues/211](url) 
But I have no idea why it must be changed
is there anyone that can explain it?

I also trained my own data three times using `tiny-yolo-voc.cfg` (but then I copied and changed the configuration based on my class) but all of my training loss will start with 107.674............
is that ok?

**Comment by t-fernandez** [comment]
Did you get this issue resolved? Im having the same problem?

**Comment by normansiboro** [comment]
I just changed the line annotations = glob.glob(str(annotations)+'*.xml') to annotations = glob.glob('*.xml') in the darkflow\utils\pascal_voc_clean_xml.py file as mention [here](https://github.com/thtrieu/darkflow/issues/211)

**Comment by rahulkrishnan98** [comment]
@normansiboro  Thanks a ton.
