### ISSUE TITLE
'ascii' codec can't decode byte - Tiny Yolo

### ISSUE THREAD

**Issue by axelboberg** [thtrieu/darkflow#441]
I'm trying to train Tiny Yolo with the corresponding weights from https://pjreddie.com/darknet/yolo/,
however, when running `flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights --train --gpu 1.0` where tiny-yolo.cfg refers to the config file from the same source as the weights, I get the error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 41: ordinal not in range(128)`.
 
What can be causing this?

My goal is to train a Yolo model either from a .pb file which I've already trained with Inception or with data in form of pngs.

**Comment by yochananscharf** [comment]
Had similar error. Caused by doing wget on the github page  instead of raw cfg file.
`wget https://github.com/pjreddie/darknet/blob/master/cfg/tiny-yolo-voc.cfg
`
is not the same as
`wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/tiny-yolo-voc.cfg`

**Comment by jingtianyilong** [comment]
Same problem here. And some more other problem
I'm running 
```
$ flow --model cfg/yolo.cfg --load bin/yolo.weights
```
Error Information
```
Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/Library/Python/2.7/site-packages/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/Library/Python/2.7/site-packages/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/Library/Python/2.7/site-packages/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/Library/Python/2.7/site-packages/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/Library/Python/2.7/site-packages/darkflow/utils/process.py", line 66, in cfg_yielder
    layers, meta = parser(model); yield meta;
  File "/Library/Python/2.7/site-packages/darkflow/utils/process.py", line 20, in parser
    lines = [line.decode() for line in lines]
```
