### ISSUE TITLE
'framework' object has no attribute 'preprocess'

### ISSUE THREAD

**Issue by LiangHao92** [thtrieu/darkflow#444]
I want to get the prediction in Json by:
`./flow --imgdir scene_test_a_images_20170922/ --model cfg/densenet201_test.cfg --load densenet201_test.weights --json`

But I get the error:
`Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/seven/darkflow/darkflow/cli.py", line 37, in cliHandler
    tfnet.predict()
  File "/home/seven/darkflow/darkflow/net/flow.py", line 123, in predict
    this_inp = self.framework.preprocess(this_inp)
AttributeError: 'framework' object has no attribute 'preprocess'`

How can I deal with it

**Comment by Gongfeng-LI** [comment]
I have the same problem while loading darknet19 weights:
`./flow --model cfg/darknet19_448.cfg --load bin/darknet19_448_conv23.weights`

**Comment by Gongfeng-LI** [comment]
It seems that this project only supports yolo/yolov2 series models by looking into the file framework.py.
