### ISSUE TITLE
Train the last n layers

### ISSUE THREAD

**Issue by Ridhwanluthra** [thtrieu/darkflow#486]
I want to choose how many layers I train. As far as I understand any layer that is edited in a `.cfg` will cause those layers to be randomly initialised but all the others will be loaded from the `.weights` and then the whole net will be fine tuned.
What I want to do is to be able to choose that I want to freeze a couple of layers and fine tune only a few or randomly initialise a few.
If this functionality exists please tell me how to use it else point me to the code where I can add this?

**Comment by thtrieu** [comment]
If I remember correctly, I buried this feature somewhere in the code for some reasons. change self.ntrain to some positive integer: https://github.com/thtrieu/darkflow/blob/master/darkflow/net/build.py#L37 and you will be able to train the last self.ntrain layers.

But use it with your own risks though. You may want to check which number is init/load/trainable by looking at what is printed to the screen.

**Comment by sheerun** [comment]
@thtrieu Changing this even by one (i.e. changing as such roof = 1 later in code), the loss is immediately up by 10 (from 3.5 to 13.5) when starting from checkpoint. This is strange as it would seem that just freezing training of some layers should not affect loss when re-starting training.

**Comment by sheerun** [comment]
Also changing roof to 22 (so just linear should be trained), changes loss even more - to 93. It seems that loading of weights is broken when roof is non-zero

**Comment by sheerun** [comment]
Or just loss value changes (to more) when training of some layers is ignored, don't know

**Comment by sheerun** [comment]
Also, when changing roof to 10, training for 50 epochs, and returning to 0, I get:

NotFoundError (see above for traceback): Key 9-convolutional/moving_variance not found in checkpoint
         [[Node: save/RestoreV2_119 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_119/tensor_names, save/RestoreV2_119/shape_and_slices)]]
         [[Node: save/RestoreV2_89/_133 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_376_save/RestoreV2_89", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/darkflow/darkflow/net/build.py", line 76, in __init__
    self.setup_meta_ops()
  File "/darkflow/darkflow/net/build.py", line 150, in setup_meta_ops
    if self.FLAGS.load != 0: self.load_from_ckpt()
  File "/darkflow/darkflow/net/help.py", line 34, in load_from_ckpt
    except: load_old_graph(self, load_point)
  File "/darkflow/darkflow/net/help.py", line 53, in load_old_graph
    'Cannot find and load {}'.format(var.name)
AssertionError: Cannot find and load 0-convolutional/kernel:0

So it seems layers from saves are missing when training limited number of layers
