### ISSUE TITLE
training on INRIA dataset

### ISSUE THREAD

**Issue by nerdykamil** [thtrieu/darkflow#489]
I am training tiny yolo model for INRIA dataset, after I start the training I get the following error, any idea what is wrong here?

Dataset size: 614
Dataset of 614 instance(s)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Training statistics: 
	Learning rate : 1e-05
	Batch size    : 16
	Epoch number  : 1000
	Backup every  : 2000
step 1 - loss 99.0089950562 - moving ave loss 99.0089950562
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/mypc/.local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/mypc/.local/lib/python2.7/site-packages/darkflow/cli.py", line 29, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/mypc/.local/lib/python2.7/site-packages/darkflow/net/flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/mypc/.local/lib/python2.7/site-packages/darkflow/net/yolo/data.py", line 126, in shuffle
    x_batch = np.concatenate(x_batch, 0)
ValueError: need at least one array to concatenate

**Comment by onurbarut** [comment]
same issue here with different datasets. If I find the solution I will provide, in the meantime check here: issues/373

**Comment by nerdykamil** [comment]
in #373 it is suggested to skip data augmentation process, is that really a good choice. Also, changing subdivisions didn't help me.

**Comment by onurbarut** [comment]
changing subdivisions didn't help me too. But when I changed the batch size from 2 to 4 I avoided the issue. However, for full version of YOLO due to memory considerations if I would have to keep the batch size as 1 or 2, I don't know what to do then...

**Comment by Ridhwanluthra** [comment]
this is probably a problem due to the data being in png format, try converting to jpg and see if it fixes your problem

**Comment by nerdykamil** [comment]
Yes, I tried that too but then got the bad Huffman code warning and termination with same error.

**Comment by paritoshp1412** [comment]
Hi! I'm getting the exact same issue here. Could anyone solve it?
I've tried increasing subdivisions and removing data augmentation as well. Nothing works.

Any help would be highly appreciated.
Thanks
