### ISSUE TITLE
AssertionError: bin/tiny-yolo.weights not found

### ISSUE THREAD

**Issue by Shubhajitdas121** [thtrieu/darkflow#513]
@dankm8
I have downloaded the "tiny-yolo.weights" to the "bin" folder inside "darkflow-master". When I run this "_./flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights_ " , it's showing the following errors:

`Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/media/shubhajit/2G4U/.Trash-1000/files/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/media/shubhajit/2G4U/.Trash-1000/files/darkflow/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/media/shubhajit/2G4U/.Trash-1000/files/darkflow/darkflow/dark/darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "/media/shubhajit/2G4U/.Trash-1000/files/darkflow/darkflow/dark/darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/tiny-yolo.weights not found`

**Comment by ranjan87** [comment]
place yolo-tiny.weights file into bin folder,hope it will work for you..

**Comment by gcovillo** [comment]
Where is this bin folder, I cannot find it!

**Comment by karthik93kulkarni** [comment]
Even I am facing the same issue and not able to find bin folder. Anyone any suggestion?

**Comment by gcovillo** [comment]
@karthik93kulkarni just create a folder called bin and place the weights in it. It works just the same :) It needs to be in the darkflow folder though
