### ISSUE TITLE
AssertionError: Cannot capture source﻿

### ISSUE THREAD

**Issue by shubhajitml** [thtrieu/darkflow#535]
I have followed the procedures and during rendering it's showing the following error:
`Finished in 24.99661946296692s

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\Interns\Real_Time_Object_Detection\darkflow-master\darkflow\cli.py", line 29, in cliHandler
    tfnet.camera()
  File "D:\Interns\Real_Time_Object_Detection\darkflow-master\darkflow\net\help.py", line 84, in camera
    'Cannot capture source'
`AssertionError: Cannot capture source﻿``

**Comment by shubhajitml** [comment]
I have fixed this.Thanks to @wangwh0204. 
```
pip uninstall opencv-python
conda remove opencv
**conda install -c anaconda opencv**

```
the root cause is opencv-python before 3.3.1 not built with FFMpeg, the newest conda opencv3.3.1 fix this.
