### ISSUE TITLE
OSError: [WinError 8] Not enough storage is available to process this command

### ISSUE THREAD

**Issue by tylerlindell** [thtrieu/darkflow#539]
getting this error when trying to run `python flow --model cfg/tiny-yolo.cfg --load bin/yolo-tiny.weights --demo videofile.avi --gpu 1.0`

the full error follows: 
```
D:\dev\darkflow\darkflow\dark\darknet.py:54: UserWarning: ./cfg/yolo-tiny.cfg not found, use cfg/tiny-yolo.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/tiny-yolo.cfg
Loading bin/yolo-tiny.weights ...
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\dev\darkflow\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "D:\dev\darkflow\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "D:\dev\darkflow\darkflow\dark\darknet.py", line 27, in __init__
    self.load_weights()
  File "D:\dev\darkflow\darkflow\dark\darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "D:\dev\darkflow\darkflow\utils\loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "D:\dev\darkflow\darkflow\utils\loader.py", line 19, in __init__
    self.load(*args)
  File "D:\dev\darkflow\darkflow\utils\loader.py", line 54, in load
    walker = weights_walker(path)
  File "D:\dev\darkflow\darkflow\utils\loader.py", line 119, in __init__
    dtype = '({})i4,'.format(4))
  File "D:\Programs\Python\Python35\lib\site-packages\numpy\core\memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [WinError 8] Not enough storage is available to process this command
```

Any help is great!

**Comment by SkullPirateTK** [comment]
My guess is that you ran out of system memory.

**Comment by tylerlindell** [comment]
I was thinking that too but I have 24G RAM and the file size is zero.
-- 
Thank you, Tyler Lindell Software Engineer 828-484-6359
TylerLindell@gmail.com

**Comment by tylerlindell** [comment]
since the file is empty, maybe `np.memmap` is having a hard time with the `mode='r'` (mode set to read-only) Check out this answer on SO: [ValueError on mmap - Python](https://stackoverflow.com/a/12748525/3187749)

**Comment by yc9690** [comment]
Hey, friend. I have a similar problem with you in pycharm.  Do you know how to solve this issue. Thank you.

**Comment by GitHubOdd** [comment]
I had this error message once, it was because i sent an image file .CR2 into mmap(), rather than  the file crated using 
 np.memmap(). The error about memory was just confusing for me.
