### ISSUE TITLE
Error : To run model on camera/webcam

### ISSUE THREAD

**Issue by Yashesh9274** [thtrieu/darkflow#540]
Hello,

As showed in, description to use the model on camera we just have to replace videofile.avi with keyword camera. 

But when i replaced videofile.avi to camera and ran the commad it gave error like ::

" OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, "

please help to solve this.

Thank you!

**Comment by pbabbicola** [comment]
Isn't this an OpenCV issue? You might have more luck asking over there.

**Comment by ahkarami** [comment]
You can refer to https://github.com/thtrieu/darkflow/issues/616

**Comment by ahkarami** [comment]
Hi,
when i run `flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --demo camera --gpu 1.0`, then I got this error:
```
Traceback (most recent call last):
  File "/home/karami/anaconda3/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/net/help.py", line 122, in camera
    single_out, img, False)
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/net/yolov2/predict.py", line 65, in postprocess
    fileName = os.path.basename(im)[:-4] + str(uuid.uuid4())
  File "/home/karami/anaconda3/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not numpy.ndarray
```
Would you please kindly help me to address this problem?
