### ISSUE TITLE
question about initializing model and reusing layers - error

### ISSUE THREAD

**Issue by johny130** [thtrieu/darkflow#55]
I am following tutorial with the goal to retrain the model on my own classes. Thanks for such awesome work!
I encounter some issues. Let me ask if what I do is correct and then why it fails:
I download any desired pair of cfg+weights from http://pjreddie.com/darknet/yolo/

Following the instructions I try to execute and get respectively errors as below:
```
# 2. To completely initialize a model, leave the --load option
./flow --model cfg/tiny-yolo.cfg 
```
```
Parsing cfg/tiny-yolo.cfg
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/john/workspace/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/john/workspace/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/home/john/workspace/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/home/john/workspace/darkflow/cfg/process.py", line 66, in cfg_yielder
    layers, meta = parser(model); yield meta;
  File "/home/john/workspace/darkflow/cfg/process.py", line 20, in parser
    lines = [line.decode() for line in lines]	
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 41: ordinal not in range(128)
```

```
# 3. It is useful to reuse the first identical layers of tiny for 3c
./flow --test test/ --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights
```
```
/home/john/workspace/darkflow/dark/darknet.py:54: UserWarning: ./cfg/yolo-tiny.cfg not found, use cfg/yolo-tiny.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/yolo-tiny.cfg
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/john/workspace/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/john/workspace/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/home/john/workspace/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/home/john/workspace/darkflow/cfg/process.py", line 66, in cfg_yielder
    layers, meta = parser(model); yield meta;
  File "/home/john/workspace/darkflow/cfg/process.py", line 17, in parser
    with open(model, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'cfg/yolo-tiny.cfg'
```

Please consider that I downloaded the yolo-tiny.cfg from darknet repository directly into /cfg, it is there.
Do I miss something? Maybe I don't fully understand concept of reusing weights with the chosen models. But choosing the same pair I supposed would work. Thanks!

**Comment by johny130** [comment]
I just realised that the weights stored in /bin were from tiny-yolo instead of yolo-tiny (those I kept outside of the /bin folder. Please delete an issue.
