### ISSUE TITLE
Divide by Zero error when training

### ISSUE THREAD

**Issue by off99555** [thtrieu/darkflow#558]
I tried to run the command
`./flow --model cfg/tiny-yolo-voc-lp.cfg --load bin/tiny-yolo-voc.weights --train --annotation data/car-annotations/ --dataset data/car --labels data/labels.txt
`
To train my own dataset which are 20 images of car with license plate annotated.
The `labels.txt` contains only one line `license plate`.
There is only one class. I changed the number of filters in the cfg file to 30.

This error occurred:
```py
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\yolo\data.py", line 113, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\yolov2\data.py", line 35, in _batch
    cx = centerx / cellx
ZeroDivisionError: float division by zero

```

I use `labelImg` software to annotate my images.
https://github.com/tzutalin/labelImg

**Comment by off99555** [comment]
This is the whole output from the command:
```py
Parsing ./cfg/tiny-yolo-voc.cfg
Parsing cfg/tiny-yolo-voc-lp.cfg
Loading bin/tiny-yolo-voc.weights ...
Successfully identified 63471556 bytes
Finished in 0.04211258888244629s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 30)
-------+--------+----------------------------------+---------------
Running entirely on CPU
cfg/tiny-yolo-voc-lp.cfg loss hyper-parameters:
        H       = 13
        W       = 13
        box     = 5
        classes = 1
        scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/tiny-yolo-voc-lp.cfg loss
Building cfg/tiny-yolo-voc-lp.cfg train op
Finished in 57.20535731315613s

Enter training ...

cfg/tiny-yolo-voc-lp.cfg parsing data/car-annotations/
Parsing for ['license plate']
[====================>]100%  img_020.xml
Statistics:
license plate: 23
Dataset size: 20
Dataset of 20 instance(s)
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\yolo\data.py", line 113, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\darkflow\net\yolov2\data.py", line 35, in _batch
    cx = centerx / cellx
ZeroDivisionError: float division by zero
2018-02-04 19:37:35.273202: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-04 19:37:38.028182: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce 940M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.66GiB
2018-02-04 19:37:38.112790: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce 940M, pci bus id: 0000:01:00.0, compute capability: 5.0)
```
I'm scratching my head right now.

**Comment by off99555** [comment]
This is an example of `img_001.xml` which is the annotation file.
```
<annotation>
	<folder>car</folder>
	<filename>img_001.jpg</filename>
	<path>D:\off99555\Documents\GitHub\[DeepLearning]\darkflow\data\car\img_001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>750</width>
		<height>560</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>license plate</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>272</xmin>
			<ymin>321</ymin>
			<xmax>473</xmax>
			<ymax>394</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by off99555** [comment]
Please tell me what is my fault.

**Comment by Adnation** [comment]
I had similar issue and when digging into it I realised that one image in training had problem. I wasn't even able to open that image in my local machine. Being this it caused training to fail. So I removed that image and it worked. 

So you can get to know that image by printing train_instance in shuffle method in file darkflow/net/yolo/data.py  

Hope that helps!!

**Comment by off99555** [comment]
@Adnation Thank you!
I found that one image in my dataset was indeed having a problem. Its perceived width and height in the `darkflow` was `[0,0]`. But I can open it in my machine's image viewer without any problems. And the viewer reported that width and height were not zeros.

But anyway, this suggested that there is something wrong with the image or how `darkflow` reads the image. Maybe it's about the fact that I use `darkflow` on Windows, isn't it?
I removed that image's annotation file and the problem is gone.

**Comment by joelunmsm2003** [comment]
@off99555 How is the width and height perceived at zero in darkflow?

**Comment by MehmetZahidGenc** [comment]
if you get error (divison by zero) when training upgrade "/content/YOLOX/yolox/evaluators/voc_evaluator.py"

line 167 => a_infer_time = 1000 * inference_time / (n_samples+1 * self.dataloader.batch_size)

line 168 => a_nms_time = 1000 * nms_time / (n_samples+1 * self.dataloader.batch_size)
