### ISSUE TITLE
The 'darkflow==1.0.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by JosephWatkins** [thtrieu/darkflow#570]
I'm having some difficulties and would appreciate any help you can provide. I've copied the weights in the bin folder and am now receiving the following error: 

(newcvtest)bash-3.2$ flow --model cfg/yolo-tiny.cfg --load bin/tiny-yolo.weights
Traceback (most recent call last):
File "/anaconda3/bin/flow", line 4, in 
import('pkg_resources').require('darkflow==1.0.0')
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 3147, in 
@_call_aside
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 3131, in _call_aside
f(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 3160, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 666, in _build_master
ws.require(requires)
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 984, in require
needed = self.resolve(parse_requirements(requirements))
File "/anaconda3/lib/python3.6/site-packages/pkg_resources/init.py", line 870, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'darkflow==1.0.0' distribution was not found and is required by the application
(newcvtest) bash-3.2$

Darkflow is installed, so I'm not certain what's wrong here. Please help!

**Comment by voqtuyen** [comment]
I have the same issue, please help?

**Comment by Melrache** [comment]
I have the same issue as well

**Comment by mohamedabdallah1996** [comment]
I faced the same issue when I was working on google colab.
I restarted the page and rerun this command
 `pip install -e .` 

this solved my issue. 
hope that help!
