### ISSUE TITLE
Reshaping Error while fine-tuning. Image size is 940, 540, 3 and I have checked #filters in last convolution layer.

### ISSUE THREAD

**Issue by sfarkya** [thtrieu/darkflow#593]
I am finetuning the yolo.cfg on [detrac](http://detrac-db.rit.albany.edu/download) dataset. The image size in the dataset is 940,540,3. I have 4 classes in the dataset and I have changed label.txt correspondingly. 

Now, as per my understanding, I have to change yolo.cgf and xml parsing code. The parsing code works fine as well. 
My yolo.cfg looks like this now. [yolo_detrac.txt](https://github.com/thtrieu/darkflow/files/1745206/yolo_detrac.txt). 

Now the issue is with reshaping of the tensors in the model, my guess is it's because of the image size. 
Here's the error.

```
Parsing ./cfg/yolo.cfg
Parsing cfg/yolo_detrac.cfg
Loading bin/yolo.weights ...
Successfully identified 203934260 bytes
Finished in 0.0095009803772s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 540, 960, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 540, 960, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 270, 480, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 270, 480, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 135, 240, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 135, 240, 128)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 135, 240, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 135, 240, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 68, 120, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 68, 120, 256)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 68, 120, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 68, 120, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 34, 60, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 34, 60, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 34, 60, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 17, 30, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 17, 30, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 17, 30, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 34, 60, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 34, 60, 64)
 Load  |  Yep!  | local flatten 2x2                | (?, 17, 30, 256)
 Load  |  Yep!  | concat [27, 24]                  | (?, 17, 30, 1280)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 17, 30, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 17, 30, 45)
-------+--------+----------------------------------+---------------
GPU mode with 0.9 usage
cfg/yolo_detrac.cfg loss hyper-parameters:
	H       = 16
	W       = 30
	box     = 5
	classes = 4
	scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/yolo_detrac.cfg loss
Building cfg/yolo_detrac.cfg train op
cfg/yolo_detrac.cfg parsing /home/sfarkya/nvidia_challenge/datasets/detrac/DETRAC-Train-Annotations-XML
Parsing for ['car', 'others', 'van', 'bus'] 
[====================>]100%  MVI_63525.xmlbreak here
Dataset of 82085 instance(s)
Training statistics: 
	Learning rate : 1e-05
	Batch size    : 16
	Epoch number  : 1000
	Backup every  : 2000
Traceback (most recent call last):
  File "/home/sfarkya/nvidia_challenge/code/darkflow/flow", line 12, in <module>
    cliHandler(sys.argv)
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/net/flow.py", line 56, in train
    fetched = self.sess.run(fetches, feed_dict)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 183600 values, but the requested shape requires a multiple of 21600
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](output, Reshape/shape)]]
	 [[Node: mul_31/_203 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_2_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Reshape', defined at:
  File "/home/sfarkya/nvidia_challenge/code/darkflow/flow", line 12, in <module>
    cliHandler(sys.argv)
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/net/build.py", line 76, in __init__
    self.setup_meta_ops()
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/net/build.py", line 139, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/net/help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "/home/sfarkya/nvidia_challenge/code/darkflow/darkflow/net/yolov2/train.py", line 56, in loss
    net_out_reshape = tf.reshape(net_out, [-1, H, W, B, (4 + 1 + C)])
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/sfarkya/tfenv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 183600 values, but the requested shape requires a multiple of 21600
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](output, Reshape/shape)]]
	 [[Node: mul_31/_203 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_2_mul_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


```
Now, if you see above Training statistics are different from the yolo cfg file and there is a reshaping error. 

Now, my question is where should I make the changes to resolve the error. More importantly, what are the others things should I change to finetune. 
@thtrieu : Can you please help?
Thanks. #ing

**Comment by sfarkya** [comment]
Solved!

**Comment by DiegoAgher** [comment]
@sfarkya how did you solve the issue?
