### ISSUE TITLE
docker run flow savepb out error

### ISSUE THREAD

**Issue by 1371030** [thtrieu/darkflow#607]
docker run -it -v /Users/admin/yolo:/yolo davvdg/darkflow-docker flow --model /yolo/tiny-yolo-voc.cfg --load /yolo/tiny-yolo-voc.weights --savepb

Rebuild a constant version ...
Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/darkflow/cli.py", line 35, in cliHandler
    tfnet.savepb(); exit('Done')
  File "/usr/local/lib/python2.7/dist-packages/darkflow/net/build.py", line 171, in savepb
    os.makedirs(os.path.dirname(name), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by run-me** [comment]
this is a python version conflict. Try using python3 if your using python2. `docker run -it -v /Users/admin/yolo:/yolo davvdg/darkflow-docker python3 flow --model /yolo/tiny-yolo-voc.cfg --load /yolo/tiny-yolo-voc.weights --savepb`

**Comment by 1371030** [comment]
thanks
