### ISSUE TITLE
try running ./flow --h facing errors

### ISSUE THREAD

**Issue by skylinetech-team** [thtrieu/darkflow#619]
hi, I followed the steps in readme.cmd (already have python 3 and tensor flow installed, and tensor flow activated)

1. pip install .
2. ./flow --h

error saying missing module "cv2"

I used mini conda installed open cv with command below

conda install opencv

now, tried again ./flow --h, seeing error below, complaining 

**ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'**

any advises ? what should be done to get this going ?

thanks much.

errors in details showing below:

**(tensorflow) Marks-MacBook-Air:darkflow markhu$ ./flow --h**

/Users/markhu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/Users/markhu/Projects/object_detection_frameworks/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/Users/markhu/Projects/object_detection_frameworks/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/Users/markhu/Projects/object_detection_frameworks/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/Users/markhu/Projects/object_detection_frameworks/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/Users/markhu/Projects/object_detection_frameworks/darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
**ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'**

**Comment by skylinetech-team** [comment]
we are trying to get this running on a brand new mac air and mac desktop.

we tried on both mac air and mac desktop:

1. following the steps mentioned in readme.cmd

2. use mini conda to install globally 

in both approach, we see this error listed above.

**Comment by skylinetech-team** [comment]
followed the suggestions from Siraj @ python3 setup.py build_ext --inplace

1. set conda env
2. install tensor flow / cython / numpy through mini conda
3. set proper conda forge channel
4. install opencv through mini conda
5. try again the steps in readme.cmd

./flow --h works now !

**Comment by skylinetech-team** [comment]
found a good way to get this going.
