### ISSUE TITLE
errors when running sample flow

### ISSUE THREAD

**Issue by skylinetech-team** [thtrieu/darkflow#620]
hi, I tried the following flow command

**./flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights**

appears **tiny-yolo.weights** not existing from the download place

so I ran again with one of the downloaded weight file:

**./flow --model cfg/tiny-yolo.cfg --load bin/yolo-tiny.weights**

got the following errors, any suggestions ?

Errors

(darkflow) Marks-MacBook-Air:darkflow markhu$ flow --model cfg/tiny-yolo.cfg --load bin/yolo-tiny.weights

/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/dark/darknet.py:54: UserWarning: ./cfg/yolo-tiny.cfg not found, use cfg/tiny-yolo.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/tiny-yolo.cfg
Loading bin/yolo-tiny.weights ...
Traceback (most recent call last):
  File "/Users/markhu/anaconda3/envs/darkflow/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/Users/markhu/anaconda3/envs/darkflow/lib/python3.6/site-packages/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 64701556 bytes, found 180357512

**Comment by skylinetech-team** [comment]
it seems that the cfg file and weight file expected to be the same name ????

the one I ran before:

cfg/tiny-yolo.cfg --load bin/yolo-tiny.weights

loader somehow expects cfg/yolo-tiny ??

**Comment by skylinetech-team** [comment]
hi, all these lines below runs ok for everyone ? we are getting errors mentioned above.

seems the cfg file and weights not match, any suggestions ?


# 1. Load tiny-yolo.weights
flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights

# 2. To completely initialize a model, leave the --load option
flow --model cfg/yolo-new.cfg

# 3. It is useful to reuse the first identical layers of tiny for `yolo-new`
flow --model cfg/yolo-new.cfg --load bin/tiny-yolo.weights
# this will print out which layers are reused, which are initialized

**Comment by skylinetech-team** [comment]
only yolo.cfg and yolo.weights works

./flow --model ./cfg/yolo.cfg --load ./bin/yolo.weights

**Comment by idhamhalim** [comment]
use this `./flow --imgdir sample_img --model cfg/tiny-yolo-voc.cfg --load tiny-yolo-voc.weights  --threshold 0 --gpu 1.0 `

**Comment by troydeng** [comment]
I think the problem is your cfg file and weights file DO not match.
Make sure they are a couple.......

**Comment by skylinetech-team** [comment]
yup, thanks, guys !

this is working 

./flow --model ./cfg/tiny-yolo-voc.cfg --load ./bin/tiny-yolo-voc.weights

**Comment by skylinetech-team** [comment]
where is tiny-yolo.cfg and tiny-yolo.weights ?
as mentioned in 1st test line
flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights

seems tiny-yolo.cfg and tiny-yolo.weights  are not in Git ?

**Comment by skylinetech-team** [comment]
also where's the cfg/yolo-new.cfg ? 

is it cloned from cfg/tiny-yolo.cfg ?

**Comment by troydeng** [comment]
@skylinetech-team 
[https://pjreddie.com/darknet/yolo/](url)

**Comment by mikeknapp** [comment]
I have the same issue. Darknet website lists two files for YOLO 2 Tiny:
`https://pjreddie.com/media/files/yolov2-tiny.weights`
and 
`https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg`

Maybe darkflow doesn't work on v2 files yet? Not sure.

Anyway, I could get something working by:

1. Download `yolo-tiny.weights` from here:
https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU

1. `python3 flow --model cfg/v1/yolo-tiny.cfg --load bin/yolo-tiny.weights --savepb --verbalise` **(Note the v1 in the cfg path)**

See also: https://github.com/pjreddie/darknet/issues/603

**Comment by DaveVoyles** [comment]
This is a project. The name of the weights file also does not match what is written in the README instructions. For example, the author lists: "bin/tiny-yolo.weights" but they are actually "yolo-tiny.weights"

**Comment by Sequential-circuits** [comment]
I put --verbalise and it still does not save the tag set

This is truly frustrating
