### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by sandeeprepakula** [thtrieu/darkflow#633]
Hi,

I am facing below issue when trying to run the test.

Forwarding 6 inputs ...
Total time = 7.751178503036499s / 6 inps = 0.7740758386159626 ips
Post processing 6 inputs ...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yolo/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ubuntu/darkflow/darkflow/cli.py", line 41, in cliHandler
    tfnet.predict()
  File "/home/ubuntu/darkflow/darkflow/net/flow.py", line 143, in predict
    enumerate(out))
  File "/home/ubuntu/anaconda3/envs/yolo/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ubuntu/anaconda3/envs/yolo/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ubuntu/anaconda3/envs/yolo/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/yolo/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/darkflow/darkflow/net/flow.py", line 142, in <lambda>
    prediction, os.path.join(inp_path, this_batch[i])))(*p),
  File "/home/ubuntu/darkflow/darkflow/net/flow.py", line 142, in <lambda>
    prediction, os.path.join(inp_path, this_batch[i])))(*p),
  File "/home/ubuntu/darkflow/darkflow/net/yolov2/predict.py", line 45, in postprocess
    boxResults = self.process_box(b, h, w, threshold)
  File "/home/ubuntu/darkflow/darkflow/net/yolo/predict.py", line 28, in process_box
    left  = int ((b.x - b.w/2.) * w)
OverflowError: cannot convert float infinity to integer

Let me know how to fix the issue.

**Comment by LucasMahieu** [comment]
It is strange, I have exactly the same issues ... An idea of the reason ?

**Comment by EinavNamer** [comment]
same here, same problem.

After training my own database, I run:

def return_predict(self, im):
    out = self.sess.run(self.out, feed_dict)[0]
    boxes = self.framework.findboxes(out)

boxes[0].w --> is inf
