### ISSUE TITLE
Input images with Only One Channel (Grayscale)

### ISSUE THREAD

**Issue by jyoonie247** [thtrieu/darkflow#640]
I am running into the issue where there is a size mismatch, where I am trying to feed in images which only have one channel, rather than the usual 3. I changed my .cfg file where I set channels to 1, but it looks like that isn't working. 

Any advice as to how I can fix this? It's a bit difficult to navigate where exactly I should be looking at to change this around. Thanks in advance!

Here is the output from running "flow":
***********************************************************************************************************

Parsing cfg/yolo-voc-SiMoNN.cfg

Loading None ...

Finished in 0.00015425682067871094s

Building net ...

Source | Train? | Layer description                | Output size

-------+--------+----------------------------------+---------------

       |        | input                            | (?, 416, 416, 1)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 32)

 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 32)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 64)

 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 64)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)

 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 128)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)

 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 52, 52, 128)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)

 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 256)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)

 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)

 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)

 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 512)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Load  |  Yep!  | concat [16]                      | (?, 26, 26, 512)

 Load  |  Yep!  | local flatten 2x2                | (?, 13, 13, 2048)

 Load  |  Yep!  | concat [26, 24]                  | (?, 13, 13, 3072)

 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)

 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 30)

-------+--------+----------------------------------+---------------

GPU mode with 1.0 usage

cfg/yolo-voc-SiMoNN.cfg loss hyper-parameters:

	H       = 13

	W       = 13

	box     = 5

	classes = 1

	scales  = [1.0, 5.0, 1.0, 1.0]

Building cfg/yolo-voc-SiMoNN.cfg loss

Building cfg/yolo-voc-SiMoNN.cfg train op

2018-03-18 11:48:05.320630: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Finished in 19.190807580947876s

Enter training ...

cfg/yolo-voc-SiMoNN.cfg parsing annotation_train

Parsing for ['sim'] 

[====================>]100%  train_nucleus5_035119.xml

Statistics:

sim: 2227886

Dataset size: 165776

Dataset of 165776 instance(s)

Training statistics: 

	Learning rate : 1e-05

	Batch size    : 16

	Epoch number  : 1000

	Backup every  : 2000

Traceback (most recent call last):

  File "/Users/jtunicorn/anaconda3/envs/neuralnets/bin/flow", line 6, in <module>

    cliHandler(sys.argv)

  File "/Users/jtunicorn/anaconda3/envs/neuralnets/lib/python3.6/site-packages/darkflow/cli.py", line 33, in cliHandler

    print('Enter training ...'); tfnet.train()

  File "/Users/jtunicorn/anaconda3/envs/neuralnets/lib/python3.6/site-packages/darkflow/net/flow.py", line 56, in train

    fetched = self.sess.run(fetches, feed_dict)

  File "/Users/jtunicorn/anaconda3/envs/neuralnets/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run

    run_metadata_ptr)

  File "/Users/jtunicorn/anaconda3/envs/neuralnets/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run

    str(subfeed_t.get_shape())))

**ValueError: Cannot feed value of shape (16, 416, 416, 3) for Tensor 'input:0', which has shape '(?, 416, 416, 1)'**

**Comment by jatinmandav** [comment]
Can you provide me the dataset you are training on so that I can test it?

**Comment by jyoonie247** [comment]
Hi jatinmandav,

Thanks for your response! I have the images and corresponding XML files in this [link](https://drive.google.com/drive/folders/1VJPqKk_WOv6wRjQpsAZbn1pRvVI_G2ai?usp=sharing).

There is only one class and one channel for each image.

**Comment by sandeeprepakula** [comment]
Can you give us the exact command used along with the cfg file used?

**Comment by ilayoon** [comment]
@jatinmandav I have made a "cv2.imread" search inside this repo. Somehow there are only three results found in three different python files:
1. darkflow/net/yolov2/predict.py
2. darkflow/net/yolo/predict.py
3. test/test_darkflow.py
All seems to be related to testing to me. I don't see why @jyoonie247 got it wrong in training.

**Comment by jatinmandav** [comment]
@ilayoon Sorry for the late reponse!
As you read the comments in [darkflow/net/yolo/predict.py in function preprocess](https://github.com/thtrieu/darkflow/blob/b2aee0000cd2a956b9f1de6dbfef94d53158b7d8/darkflow/net/yolo/predict.py#L49), It has been stated that if allobj param in given, the image is read for training purpose else for prediction. Hope this clears the doubt.!

**Comment by benn94** [comment]
thank you @jatinmandav

**Comment by jatinmandav** [comment]
You're welcome @benn94 .! @jyoonie247 if you don't have any other confusion or doubt, remember to close the issue. :)

**Comment by jatinmandav** [comment]
Hi @groot-1313 
On line 10 in [darkflow/utils/im_transform.py](https://github.com/thtrieu/darkflow/blob/b2aee0000cd2a956b9f1de6dbfef94d53158b7d8/darkflow/utils/im_transform.py#L10), the comment reads `random amplify each channel`.  This is done for all the three channels and not for a single channel. hence the error.

**Comment by fkoorc** [comment]
hello I tried train the grayscale images and also success.
but the accuracy is pretty bad did anyone get good results?
Because I also tried 3 channel images but changed 2 channels to all 0
so I am not sure is the parameter too small?(3 times reduced)
or is the algorithm I revised did something wrong Thx a lot
