### ISSUE TITLE
How to train darkflow on floydhub

### ISSUE THREAD

**Issue by alfamousts** [thtrieu/darkflow#643]
Hello everyone, I have tried to train darkflow using floydhub. I have already copy the file from my PC to the floydhub. Then i was using this command to train the data in floydhub.

`floyd run flow.py --model cfg/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc.weights --train --annotation new_model_data/annotations --dataset new_model_data/images --gpu 0.8 --epoch 300`

And nothing was happen except an error shows like this

> Error: no such option: --model

Sorry if my question is too basic that can be solved, I just can understand how to uses floydhub because i am very new to use floydhub. I am very glad if anyone can help me to fix this problem.

**Comment by EKELE-NNOROM** [comment]
Hi alfamousts, I think you have to install cython or use pip. Check out this link
https://keponk.wordpress.com/2017/12/07/siraj-darkflow/

**Comment by kribby** [comment]
@alfamousts Did you manage to get this working?
Im trying to train my model on floydhub too

**Comment by EKELE-NNOROM** [comment]
No I didn't but I think you'd need to find out how to organize the folder for floydhub. Do read the link I sent you.
Happy hacking!

**Comment by kribby** [comment]
How do I access checkpoint files from another directory?

I have trained the model locally on my laptop and want to continue on Floydhub. However Floydhub won't allow me to upload these file with the code. I have to load the checkpoint files as a dataset. Therefore I need to be able to specify a path to the location of the checkpoint files when I enter the command to train the model.

When I initialize the training I can provide a path to the checkpoint file e.g. 


python flow --model cfg/model.cfg --load ../../Dropbox/ckpt/checkpoint files.profile --annotation ../../Dropbox/modeldataset/data_repo/treated/annotations  --dataset ../../Dropbox/modeldataset/data_repo/treated/_data_Clean --epoch 1000 --lr 9e-3 --trainer adam --save 7650 --momentum 0.9   


This incurs the following error:
Traceback (most recent call last):                                                                                                                                               File "flow", line 6, in <module>                                                                                                                                                 cliHandler(sys.argv)                                                                                                                                                         File "C:\Users\krisb\Documents\darkflow\darkflow\cli.py", line 26, in cliHandler                                                                                                 tfnet = TFNet(FLAGS)                                                                                                                                                         File "C:\Users\krisb\Documents\darkflow\darkflow\net\build.py", line 58, in __init__                                                               


I have tried this with every type of file .profile meta .index e.t.c. 

How do I overcome this?

Thanks in advance

K

**Comment by EKELE-NNOROM** [comment]
I haven't successfully trained on floydhub but you can use this format in
the screen shot. You command does not seem to follow the format on floydhub
requires. Use this link for more guidance.

https://medium.com/du-phan/build-a-not-so-real-time-object-detection-app-with-raspberry-pi-117cb6f2c12b

More so, to load from last checkpoint on a local machine use something like
"

# Resume the most recent checkpoint for training
flow --train --model cfg/yolo-new.cfg --load -1

" but I'm not sure it's the same with floydhub

Thank you, please let me know how you'd solve it eventually. Happy
hacking!!!
