### ISSUE TITLE
AssertionError: Over-read bin/yolo-voc.weights

### ISSUE THREAD

**Issue by junxuezheng** [thtrieu/darkflow#644]
hp2@hp2:~/jx/darkflow-master$ flow --imgdir sample_img/ --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --gpu 1.0

Parsing ./cfg/yolo-voc.cfg
Parsing cfg/yolo-voc.cfg
Loading bin/yolo-voc.weights ...
Traceback (most recent call last):
  File "/home/hp2/.local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 70, in load
    val = walker.walk(new.wsize[par])
  File "/home/hp2/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 127, in walk
    'Over-read {}'.format(self.path)
## AssertionError: Over-read bin/yolo-voc.weights

I want to run yolo v2 on voc 2007 data using yolo-voc.cfg. and i download yolo-voc.weights file from https://pjreddie.com/.
where can i get the right weights about yolo-voc.cfg?

**Comment by jatinmandav** [comment]
Hi junxuezheng,
I believe you will find all the weights here [https://pjreddie.com/darknet/yolo/](https://pjreddie.com/darknet/yolo/), just find the appropriate weight along the cfg file.

**Comment by junxuezheng** [comment]
@jatinmandav 
hey,jatinmandav
you are right.
I download the yolo-voc.cfg in  darknet. replacing the yolo-voc.cfg in darkflow. it is working now.
thanks.

**Comment by bit-scientist** [comment]
Hi, @junxuezheng. I also have this assertion error. I have trained a model for only one class using darknet yolo3 given [here.](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects) Now I have a cfg file and .weights file. There are helmet_15000.cfg and helmet_15000.weights files. When I run I have similar error like you mentioned
`'Over-read {}'.format(self.path)

AssertionError: Over-read darkflow\bin\helmet_15000.weights` How should I solve this issue? Thanks

**Comment by iseegr8tfuldeadppl** [comment]
It seems that the PJ Reddie files are not fully compatible, so I have to download the pre built weights from the provided link in the README: https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU
