### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by alfamousts** [thtrieu/darkflow#662]
Hello everyone, I've got problem when using weights that i've been trained. When training, i am using code from darknet [made by alexey ](https://github.com/AlexeyAB/darknet) . I used the darkflow code to load this weights but there  was some errors like this.

> Traceback (most recent call last):
>   File "D:\TA\YOLO\darkflow-master\part4_video_2.py", line 13, in <module>
>     tfnet = TFNet(options)
>   File "D:\TA\YOLO\darkflow-master\darkflow\net\build.py", line 64, in __init__
>     self.framework = create_framework(*args)
>   File "D:\TA\YOLO\darkflow-master\darkflow\net\framework.py", line 59, in create_framework
>     return this(meta, FLAGS)
>   File "D:\TA\YOLO\darkflow-master\darkflow\net\framework.py", line 15, in __init__
>     self.constructor(meta, FLAGS)
>   File "D:\TA\YOLO\darkflow-master\darkflow\net\yolo\__init__.py", line 24, in constructor
>     ).format(meta['model'])
> AssertionError: labels.txt and cfg/yolo-loreal.cfg indicate inconsistent class numbers

Anyone can help me ?

**Comment by melonetern** [comment]
have the same problem. 
I change the `classes=2`, and the last `filters=35` which is (2+5)*5, and in the labels.txt I only have
raccoon
kangaroo
I use `--labels ../mylabels_path` to train my own pictures.
But I got this error:
AssertionError: lables.txt and ../datasets/train/yolo.cfg indicate inconsistent class numbers.
I don't understand, did I miss something?

**Comment by eljirg** [comment]
Found the same error, using the https://github.com/thtrieu/darkflow code

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\eljir\DS\darkflow-master\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\eljir\DS\darkflow-master\darkflow\net\build.py", line 64, in __init__
    self.framework = create_framework(*args)
  File "C:\Users\eljir\DS\darkflow-master\darkflow\net\framework.py", line 59, in create_framework
    return this(meta, FLAGS)
  File "C:\Users\eljir\DS\darkflow-master\darkflow\net\framework.py", line 15, in __init__
    self.constructor(meta, FLAGS)
  File "C:\Users\eljir\DS\darkflow-master\darkflow\net\yolo\__init__.py", line 24, in constructor
    ).format(meta['model'])
AssertionError: labels.txt and cfg/yolov2-tiny.cfg indicate inconsistent class numbers

Changing the classes in cfg file to match the number of classes in the label.txt fixed the issues

**Comment by ocaduacelab** [comment]
Why does that solve it though? What does the number of classes in the cfg need to match the labels.txt file?

**Comment by fogonthedowns** [comment]
Did you guys figure this out?

**Comment by GGDRriedel** [comment]
The problem still persists with weights and models downloaded from 
https://pjreddie.com/darknet/yolo/

**Comment by KumarHalder** [comment]
please copy the cfg file, give it a new name, edit the classes, and then use the new cfg file. Sometimes when you define the same name as the .cfg file, I guess the model does not check on the edited file, it checks the original one, causing the mismatch.
