### ISSUE TITLE
video

### ISSUE THREAD

**Issue by linydf** [thtrieu/darkflow#663]
I want to test the local video, which path should I put the video on?  thanks

**Comment by abagshaw** [comment]
You can set darkflow to load a video from any path.

```
flow --model cfg/yolo.cfg --load bin/yolo.weights --demo path/to/file/video.avi
```

**Comment by ahkarami** [comment]
Dear @abagshaw,
when i run `flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --demo camera --gpu 1.0`, then I got this error:
```
Traceback (most recent call last):
  File "/home/karami/anaconda3/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/net/help.py", line 122, in camera
    single_out, img, False)
  File "/home/karami/PycharmProjects/TensorFlow Projects/YoLo-DarkFlow Object Detector/darkflow/darkflow/net/yolov2/predict.py", line 65, in postprocess
    fileName = os.path.basename(im)[:-4] + str(uuid.uuid4())
  File "/home/karami/anaconda3/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not numpy.ndarray
```
Would you please kindly help me to address this problem?

**Comment by djsurani** [comment]
@abagshaw  see code for path properly .

**Comment by djsurani** [comment]
@abagshaw  numpy issu also there in your pc
