### ISSUE TITLE
Odd MemoryError

### ISSUE THREAD

**Issue by kent-anderson** [thtrieu/darkflow#674]
Pulling what little hair I have left out... Right now, just simply attempting to get the sample image to process.

These are weight and config that work wonderfully on all other machines (x86 style)

/opt/darkflow$ sudo flow --imgdir sample_img/ --model cfg/tiny-yolo-voc_2.cfg --load bin/tiny-yolo-voc_39100.weights --json

Parsing cfg/tiny-yolo-voc_2.cfg
Loading bin/tiny-yolo-voc_39100.weights ...
Successfully identified 63143556 bytes
Finished in 0.027110815048217773s

Building net ...
--- Net Builds Fine
Running entirely on CPU
Finished in 7.55274510383606s

Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/opt/darkflow/darkflow/cli.py", line 41, in cliHandler
    tfnet.predict()
  File "/opt/darkflow/darkflow/net/flow.py", line 129, in predict
    feed_dict = {self.inp : np.concatenate(inp_feed, 0)}    
MemoryError

/opt/darkflow$ free
              total        used        free      shared  buff/cache   available
Mem:        3903128     1488476     1105964     1063272     1308688     1290488
Swap:             0           0           0

Why am I getting a "MemoryError"  Does not tell me much in terms of where the actual breakdown might be.

This is a configuration that is used in many other instances.
Only different is I am attempting to this on a firefly.  Similar to a Pi or Jetson-TX (no GPU though)
All other systems run w/o GPU also.  That is our current model for testing.  Will always speed up with GPU

Thanks in advance.

**Comment by kent-anderson** [comment]
OK.  After some more testing, it actually appeared to be a "Out Of Memory" error.  To many processor hogging resources.  

On a side note, it appeared that I needed about 1.5GB of free RAM for this process to run.

Thanks for reading.  This can be closed.
