### ISSUE TITLE
an error to convert yolo-voc.weights to a pb

### ISSUE THREAD

**Issue by kaishijeng** [thtrieu/darkflow#69]
An error occurred when using the following command to convert yolo-voc.weights to a pb format
./flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --savepb --verbalise=True.
The same command is running OK for tiny-yolo-voc.weights

Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/fc/2TB/src/darkflow/net/build.py", line 50, in __init__
    self.build_forward()
  File "/home/fc/2TB/src/darkflow/net/build.py", line 70, in build_forward
    state = op_create(*args)
  File "/home/fc/2TB/src/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/home/fc/2TB/src/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/home/fc/2TB/src/darkflow/net/ops/simple.py", line 16, in forward
    self.out = tf.concat(routes_out, 3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by johny130** [comment]
Which tensorflow version are you using? 
You get an error related to 

```
`File "/home/fc/2TB/src/darkflow/net/ops/simple.py", line 16, in forward
self.out = tf.concat(routes_out, 3)`
```

According to [official website], (https://www.tensorflow.org/install/migration)
```
tf.concat
keyword argument concat_dim should be renamed to axis
arguments have been reordered to tf.concat(values, axis, name='concat').
```
So make sure the order of the arguments is correct.

**Comment by rainmat** [comment]
Which tensorflow version are you using? 
You get an error related to 

```
File "/home/fc/2TB/src/darkflow/net/ops/simple.py", line 16, in forward
self.out = tf.concat(routes_out, 3)
```

According to https://www.tensorflow.org/install/migration :
```
tf.concat
keyword argument concat_dim should be renamed to axis
arguments have been reordered to tf.concat(values, axis, name='concat').
```
So make sure the order of the arguments is correct.

**Comment by kaishijeng** [comment]
I use 0.12.1. should I try 1.0?

Thanks,

**Comment by thtrieu** [comment]
Please see the `README`. It is Python3, Tensorflow 1.0 and openCV 3.1.0

**Comment by kaishijeng** [comment]
After upgrading tensorflow to 1.0, the issue is gone.

Thanks,

**Comment by thtrieu** [comment]
Currently no. A contribution is welcomed though.
