### ISSUE TITLE
Failed running camera demo

### ISSUE THREAD

**Issue by shawnau** [thtrieu/darkflow#71]
When running camera demo

`./flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --demo camera`

There'e no problem loading the net, but I encountered this at the end of detection:

```bash
Traceback (most recent call last):
  File "./flow", line 50, in <module>
    tfnet.camera(FLAGS.demo)
  File "/home/chobits/darkflow/net/help.py", line 72, in camera
    processed = self.framework.postprocess(net_out, frame, False)
  File "/home/chobits/darkflow/net/yolov2/test.py", line 100, in postprocess
    img_name = os.path.join(outfolder, im.split('/')[-1])
AttributeError: 'numpy.ndarray' object has no attribute 'split'
```

 - For some reason I'm using python 2.7.12, maybe this is the problem? I'm newbie...I'd appreciate it if someone would give me some explanation about this
 - I fixed it by just adding a line to bypass this if `im` is `numpy.ndarray`
 - Just post it if someone encountered the same problem using camera demo under python2.7....I'd switch to python3 asap

**Comment by mhnatiuk** [comment]
Same here:
python flow --model cfg\v2.0\tiny-yolo.cfg --load bin\tiny-yolo.weights --demo camera
``
Running entirely on CPU
Finished in 1.6188035011291504s

Press [ESC] to quit demo
Traceback (most recent call last):
  File "flow", line 50, in <module>
    tfnet.camera(FLAGS.demo)
  File "C:\Users\mhnatiuk\Documents\darkflow\darkflow\net\help.py", line 72, in camera
    processed = self.framework.postprocess(net_out, frame, False)
  File "C:\Users\mhnatiuk\Documents\darkflow\darkflow\net\yolov2\test.py", line 99, in postprocess
    img_name = os.path.join(outfolder, im.split('/')[-1])
AttributeError: 'numpy.ndarray' object has no attribute 'split'

**Comment by jiangyuguang** [comment]
thinkpad T460 ，ubuntu14.04，opencv3.1.0，python3.4
when run demo camera
python3 ./flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo-voc.weights --demo camera

Press [ESC] to quit demo
Traceback (most recent call last):
  File "./flow", line 50, in <module>
    tfnet.camera(FLAGS.demo)
  File "/home/jiangyuguang/Project/darkflow-master/net/help.py", line 72, in camera
    processed = self.framework.postprocess(net_out, frame, False)
  File "/home/jiangyuguang/Project/darkflow-master/net/yolov2/test.py", line 99, in postprocess
    img_name = os.path.join(outfolder, im.split('/')[-1])
AttributeError: 'numpy.ndarray' object has no attribute 'split'

demo use laptop‘s camera，not a usb webcam ，is this the problem？

**Comment by thtrieu** [comment]
Hey guys, sorry for late reply. It's a bug after adding support for JSON output. Please update the code.
