### ISSUE TITLE
ModuleNotFoundError: No module named 'nms' Error!!

### ISSUE THREAD

**Issue by hbzhang** [thtrieu/darkflow#740]
I just pull the darkflow today and run it using both python and Annocoda, Mincoda. 

I also followed this tutorial

https://keponk.wordpress.com/2017/12/07/siraj-darkflow/

I have spent a whole day on this, but I still have this error regardless what I do:

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/hdd/students/issac/Pedestrian-Detection-using-Darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/hdd/students/issac/Pedestrian-Detection-using-Darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/hdd/students/issac/Pedestrian-Detection-using-Darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/hdd/students/issac/Pedestrian-Detection-using-Darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/hdd/students/issac/Pedestrian-Detection-using-Darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
  File "darkflow/cython_utils/cy_yolo_findboxes.pyx", line 1, in init darkflow.cython_utils.cy_yolo_findboxes
    import numpy as np
ModuleNotFoundError: No module named 'nms'

**Comment by linuxandchill** [comment]
@hbzhang did you ever figure this out?

**Comment by ItaiShchorry** [comment]
same problem, please help

**Comment by SCloves** [comment]
Same problem here, I also followed the keponk's tutorial.

**Comment by annasba** [comment]
I'm facing the same problem, anyone find a solution?

**Comment by Rockstar256** [comment]
Check after installing darkflow, in darkflow/cython_utils whether you have nms.so(unix) or nms.pyd(windows). If not then try cythonizing each nms.pyx file.
And make sure you have gcc compiler and cython installed in your environment.
