### ISSUE TITLE
training tiny-yolo 

### ISSUE THREAD

**Issue by anas-sinjab** [thtrieu/darkflow#753]
hello all i am trying to train a new model with 3 classes 
face, fist palm 
i am getting this issue 

cfg/tiny-yolo-voc-3c.cfg parsing new-model-data/annotations
Parsing for ['face', 'fist', 'palm'] 
Traceback (most recent call last):
  File "/home/sinjab/.virtualenvs/cv/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/net/flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/net/yolo/data.py", line 97, in shuffle
    data = self.parse()
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/net/yolo/data.py", line 18, in parse
    dumps = pascal_voc_clean_xml(ann, meta['labels'], exclusive)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/utils/pascal_voc_clean_xml.py", line 22, in pascal_voc_clean_xml
    annotations = glob.glob(str(annotations)+'*.xml')
  File "/usr/lib/python3.5/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.5/glob.py", line 54, in _iglob
    yield from glob1(dirname, basename)
  File "/usr/lib/python3.5/glob.py", line 90, in glob1
    return fnmatch.filter(names, pattern)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/home/sinjab/.virtualenvs/cv/lib/python3.5/sre_parse.py", line 575, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range s-a at position 74

**Comment by anas-sinjab** [comment]
![screenshot from 2018-05-12 06-08-52](https://user-images.githubusercontent.com/39134844/39949087-5eba5312-55ab-11e8-8024-91b1936232c5.png)

**Comment by off99555** [comment]
I got a similar error. I think it's about file name issue.
If your file contains symbols like hyphens (-) it won't work.
Here's the error line:
`annotations = glob.glob(str(annotations)+'*.xml')`
I am not sure what it does but I changed it to `annotations = glob.glob('*.xml')` and it worked for me.
Check it in
```
File "/home/sinjab/.virtualenvs/cv/lib/python3.5/site-packages/darkflow/utils/pascal_voc_clean_xml.py", line 22, in pascal_voc_clean_xml
```

**Comment by tonnkie** [comment]
I comment this line. And it works.

**Comment by adrianosantospb** [comment]
Hello, I'm trying to train my model and I'm receiving this message "sre_constants.error: bad character range 9-0 at position 15" in the execution process. Anybody here faced this problem?
