### ISSUE TITLE
How do I use the tensorflow debugger (tfdbg) to overcome Nan problem

### ISSUE THREAD

**Issue by kribby** [thtrieu/darkflow#771]
Hi 

My model will not converge and I keep getting a whole load of Nans even though I decrease the LR to around 1e-17

Tensorflow's debugger apparently assists in finding the sources of these Nans and therefore I would like to try it out.

I can't seem to get it to work.

This is the command I use

python -m flow.debug --model cfg/tiny-yolo-voc-7c-alpha.cfg --train --load 1860 --annotation ../../Dropbox/annotations --dataset ../../Dropbox/data --epoch 5 --lr 0.90e-2 --trainer rmsprop --save 50 --batch 50 --summary /summary --debug 

And I have also amended build.py by adding the following line at the top of the file

from tensorflow.python import debug as tf_debug #New Line here

as well as replacing 
self.sess =tf.Session(config = tf.ConfigProto(**cfg)) 

with

self.sess = tf_debug.LocalCLIDebugWrapperSession(config = tf.ConfigProto(**cfg))

This doesn't work and I get the following error

C:\Users\username\AppData\Local\Programs\Python\Python36\python.exe: Error while finding module specification for 'flow.debug' (ModuleNotFoundError: No module named 'flow') 

Thanks in advance

K

**Comment by kribby** [comment]
So i have tried adapting this video tutorila to the darkflow code
https://youtu.be/XcHWLsVmHvk?t=9m11s


I pasted the following lines

from tensorflow.python import debug as tf_debug #added line 
to line 2 (after import tensorflow as tf) 
and 
		self.sess = tf_debug.TensorBoardDebugWrapperSession(self.sess, "DESKTOP-J0L4S82:7000")

to line 147 in darkflow/net/build.py

This didn't work and the following error message was shown 

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\krisb\Documents\darkflow\darkflow\cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "C:\Users\krisb\Documents\darkflow\darkflow\net\flow.py", line 57, in train
    loss = fetched[1]
TypeError: 'UnimplementedError' object does not support indexing



Any solutions?

**Comment by caisq** [comment]
Hi there, 

`tf_debug.LocalCLIDebugWrapperSession` should be called with a `tf.Session` object as the first argument, not a ConfigProto. Can you create a `tf.Session` first, like

```python
self.sess = tf.Session(config = tf.ConfigProto(**cfg))
self.sess = tf_debug.LocalCLIDebugWrapperSession(self.sess)
```

**Comment by kribby** [comment]
Hi @caisq thanks for your suggestion.

So I implemented your suggestion in line 145-146 in [https://github.com/thtrieu/darkflow/blob/master/darkflow/net/build.py](url)


           `
		self.sess = tf.Session(config = tf.ConfigProto(**cfg))
		self.sess = tf_debug.LocalCLIDebugWrapperSession(self.sess, "DESKTOP-J0L4S82:7000")
		self.sess.run(tf.global_variables_initializer())`

However this error occured: 


> Traceback (most recent call last):
>   File "flow", line 6, in <module>
>     cliHandler(sys.argv)
>   File "C:\Users\krisb\Documents\darkflow\darkflow\cli.py", line 26, in cliHandler
>     tfnet = TFNet(FLAGS)
>   File "C:\Users\krisb\Documents\darkflow\darkflow\net\build.py", line 77, in __init__
>     self.setup_meta_ops()
>   File "C:\Users\krisb\Documents\darkflow\darkflow\net\build.py", line 151, in setup_meta_ops
>     self.sess.run(tf.global_variables_initializer())
>   File "C:\Users\krisb\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\debug\wrappers\framework.py", line 455, in run
>     is_callable_runner=bool(callable_runner)))
>   File "C:\Users\krisb\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\debug\wrappers\local_cli_wrapper.py", line 253, in on_run_start
>     self._prep_cli_for_run_start()
>   File "C:\Users\krisb\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\debug\wrappers\local_cli_wrapper.py", line 275, in _prep_cli_for_run_start
>     self._run_cli = ui_factory.get_ui(self._ui_type)
>   File "C:\Users\krisb\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 71, in get_ui
>     available_ui_types=available_ui_types)
>   File "C:\Users\krisb\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 69, in get_ui
>     raise ValueError("Exhausted all fallback ui_types.")
> ValueError: Exhausted all fallback ui_types.

**Comment by kribby** [comment]
@caisq 
Included these three lines in in line 145-146 in [https://github.com/thtrieu/darkflow/blob/master/darkflow/net/build.py](url)

           `sess = tf.Session()
		self.sess = tf.Session(config = tf.ConfigProto(**cfg))
		self.sess = tf_debug.LocalCLIDebugWrapperSession(self.sess, "DESKTOP-J0L4S82:7000")
		self.sess.run(tf.global_variables_initializer())`


Now I get the CLI working

![image](https://user-images.githubusercontent.com/7774494/40509612-0760c9ca-5f92-11e8-9ae8-f4602d6e9f75.png)

**Comment by kribby** [comment]
I still can't get the "TensorBoardDebugWrapperSession" to work

**Comment by caisq** [comment]
What's the problem you are having with "TensorBoardDebugWrapperSession"?

**Comment by kribby** [comment]
Hi @caisq 

So I want to do what you did in this video [https://youtu.be/XcHWLsVmHvk?t=8m31s](url)

So I have amended the code in [https://github.com/thtrieu/darkflow/blob/master/darkflow/net/build.py](url) to include
![image](https://user-images.githubusercontent.com/7774494/40546846-3e99e87c-6028-11e8-95f7-51ff41c09ec3.png)


![image](https://user-images.githubusercontent.com/7774494/40546800-1938e24a-6028-11e8-8bbf-3e67a3d73a08.png)

The code then builds successfully but when I run the trained model I get the following error


![image](https://user-images.githubusercontent.com/7774494/40546704-d9c51dc2-6027-11e8-93e1-ad294b52efee.png)
