### ISSUE TITLE
AssertionError: expect 63143560 bytes, found 63471556

### ISSUE THREAD

**Issue by shubhajitml** [thtrieu/darkflow#781]
Still having the same error after redownloading `tiny-yolo-voc-4c.cfg` and `tiny-yolo-voc-4c.weights` files :
```
Parsing ./cfg/tiny-yolo-voc-4c.cfg
Parsing cfg/tiny-yolo-voc-4c.cfg
Loading bin/tiny-yolo-voc-4c.weights ...
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ubuntu/darkflow-master/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/ubuntu/darkflow-master/darkflow/net/build.py", line 59, in __init__
    darknet = Darknet(FLAGS)
  File "/home/ubuntu/darkflow-master/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/ubuntu/darkflow-master/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/ubuntu/darkflow-master/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/ubuntu/darkflow-master/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/ubuntu/darkflow-master/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 63143556 bytes, found 63471556
```

**Comment by shubhajitml** [comment]
Got it!
Only changing the file name `tiny-yolo-voc-4c.weights` to `tiny-yolo-voc.weights` with remaining the other configurations same, fixed the issue.
So, closing this thread.

**Comment by ideaRunner** [comment]
Why the file name have such influences?
I got a similar error, I trained my own dataset...
So no idea how to change the file name

**Comment by jackweiwang** [comment]
@shubhajitml 
I got similar error,  can you tell me how to solve
I trained my dataset  and 4 classes yolov2-tiny-voc

./darknet detector train cfg/voc.data cfg/yolov2-tiny-voc.cfg  cfg/darknet19_448.conv.23 
and used 
python3 ./flow --model cfg/tiny-yolo-voc.cfg  --load ../darknet/backup/yolov2-tiny-voc_final.weights  --savepb 
tiny-yolo-voc.cfg change filters 45 and class 4.
