### ISSUE TITLE
Import error  undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolB5cxx11Eb

### ISSUE THREAD

**Issue by juankcl** [thtrieu/darkflow#787]
Hello, I tried for days use the darkflow, install, but in the demos create issues, the most recently is an undefinded symbol in protobuf, i dont know what the problem

I have a AMD lenovo with ubuntu 18.04 LTS i dont know if exist some issue with  this...

i show the code ...

```
juank@lenovo:~/YOLO_Object_Detection$ flow --model cfg / yolo-new.cfg --cargar bin / yolo-new.weights --demo camera
Traceback (most recent call last):
  File "/home/juank/anaconda3/bin/flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/juank/anaconda3/lib/python3.6/site-packages/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/juank/anaconda3/lib/python3.6/site-packages/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/juank/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/juank/anaconda3/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolB5cxx11Eb



juank@lenovo:~/YOLO_Object_Detection$ flow --model cfg / yolo-new.cfg --cargar bin / yolo-new.weights --demo videofile.avi
Traceback (most recent call last):
  File "/home/juank/anaconda3/bin/flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/juank/anaconda3/lib/python3.6/site-packages/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/juank/anaconda3/lib/python3.6/site-packages/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/juank/anaconda3/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/juank/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/juank/anaconda3/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolB5cxx11Eb
```

I hope solve this and dont understand the problem,,, thank you very much :)

**Comment by sinhaharsh** [comment]
conda update libprotobuf
