### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cfg/tolo-new.cfg'

### ISSUE THREAD

**Issue by DaveVoyles** [thtrieu/darkflow#794]
OS:Ubuntu Deep Learning VM on Azure

Follow the instructions to this point: 

```
# Download the Pascal VOC dataset:
curl -O https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar

# An example of the Pascal VOC annotation format:
vim VOCdevkit/VOC2007/Annotations/000001.xml

# Train the net on the Pascal dataset:
flow --model cfg/yolo-new.cfg --train --dataset "~/VOCdevkit/VOC2007/JPEGImages" --annotation "~/VOCdevkit/VOC2007/Annotations"
```

Afterwards, it returns:

```
davevoyles@dv-dlvm-ubuntu:/tmp/mozilla_davevoyles0/darkflow-master$ curl -O https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  430M  100  430M    0     0  34.9M      0  0:00:12  0:00:12 --:--:-- 38.0M
davevoyles@dv-dlvm-ubuntu:/tmp/mozilla_davevoyles0/darkflow-master$ tar xf VOCtest_06-Nov-2007.tar
davevoyles@dv-dlvm-ubuntu:/tmp/mozilla_davevoyles0/darkflow-master$ flow --model cfg/tolo-new.cfg --train --dataset "~/VOCdevkit/VOC2007/JPEGImages" --annotation "~/VOCdevkit/VOC2007/Annotations"
/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Parsing cfg/tolo-new.cfg
Traceback (most recent call last):
  File "/anaconda/envs/py35/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/tmp/mozilla_davevoyles0/darkflow-master/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/utils/process.py", line 66, in cfg_yielder
    layers, meta = parser(model); yield meta;
  File "/tmp/mozilla_davevoyles0/darkflow-master/darkflow/utils/process.py", line 17, in parser
    with open(model, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cfg/tolo-new.cfg'
```

**Comment by DaveVoyles** [comment]
I realize now that you need the weight files, but it's not clear from the README. I'd recommend including in the instructions as one of the steps. Ran into someone who had the exact same problem.

**Comment by sharoseali** [comment]
its yolo.cfg ...... not tolo

**Comment by Francisobiagwu** [comment]
So what is the right command?

**Comment by orolfat99** [comment]
https://github.com/pypa/pip/issues/7070#issue-497214502
I have similar problem, and still not solved .
