### ISSUE TITLE
ImportError: /home/kei/darkflow/darkflow/cython_utils/cy_yolo_findboxes.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by keides2** [thtrieu/darkflow#814]
I have an ImportError:

(tensorflow) kei@giga:~/darkflow$ ./flow --model cfg/yolo.cfg --load yolo.weights --savepb
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/kei/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/kei/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/home/kei/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/home/kei/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/home/kei/darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ImportError: /home/kei/darkflow/darkflow/cython_utils/cy_yolo_findboxes.so: undefined symbol: _Py_ZeroStruct

**Comment by tomepetty** [comment]
I'm getting this error: 

flow --model cfg/yolov2-tiny-voc.cfg --load bin/yolov2-tiny-voc.weights --savepb ;\

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/tome/.local/bin/flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/tome/ncappzoo_2.04.00.06/ncappzoo/tensorflow/TinyYoloV2_NCS/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/tome/ncappzoo_2.04.00.06/ncappzoo/tensorflow/TinyYoloV2_NCS/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/home/tome/ncappzoo_2.04.00.06/ncappzoo/tensorflow/TinyYoloV2_NCS/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/home/tome/ncappzoo_2.04.00.06/ncappzoo/tensorflow/TinyYoloV2_NCS/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/home/tome/ncappzoo_2.04.00.06/ncappzoo/tensorflow/TinyYoloV2_NCS/darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ImportError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

**Comment by keides2** [comment]
After running $ pip install cython, I think that no error came out.

**Comment by PrinceOfDorne** [comment]
I have the same issue. $pip install python is not working.

**Comment by kenkyulab** [comment]
setup.pyを実行する際に$python setup.pyではなく$python3 setup.pyで実行すればうまくいくかもしれません
