### ISSUE TITLE
Can I put the python program outside the darkflow root folder?

### ISSUE THREAD

**Issue by SinLok** [thtrieu/darkflow#821]
My original setting like this:
```
darkflow_api
    cfg
    darkflow
    build
    labels.txt
    main.py
```
main.py can run successful to detect the object. However, when I put main.py outside the darkflow_api folder. It cause the following problem:
```
main.py
darkflow_api
    cfg
    darkflow
    build
    labels.txt
```

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from video_capture import VideoCapture
  File "C:\Users\Jack\Desktop\Uto\video_capture.py", line 3, in <module>
    from video_processing import ObjectDetection
  File "C:\Users\Jack\Desktop\Uto\video_processing.py", line 1, in <module>
    from darkflow_api.darkflow.net.build import TFNet
  File "C:\Users\Jack\Desktop\Uto\darkflow_api\darkflow\net\build.py", line 7, in <module>
    from .framework import create_framework
  File "C:\Users\Jack\Desktop\Uto\darkflow_api\darkflow\net\framework.py", line 1, in <module>
    from . import yolo
  File "C:\Users\Jack\Desktop\Uto\darkflow_api\darkflow\net\yolo\__init__.py", line 2, in <module>
    from . import predict
  File "C:\Users\Jack\Desktop\Uto\darkflow_api\darkflow\net\yolo\predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
  File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.cython_utils.cy_yolo_findboxes
ModuleNotFoundError: No module named 'darkflow'
```

**Comment by ProtossDragoon** [comment]
Me either :(
