### ISSUE TITLE
Installation Instructions for Windows 10

### ISSUE THREAD

**Issue by JaronrH** [thtrieu/darkflow#849]
Just in case anyone else had issues getting Darkflow running on Windows 10, here's the steps that I was able to use to get it working.  Hopefully it will help save time for someone else!

1) Install Python **3.5**
2) [Optional] Create virtualenv
3) Install Tensorflow: pip3 install --upgrade tensorflow
4) Install cython: pip3 install cython
5) Install opencv: pip3 install opencv-python
6) Build: python setup.py build_ext --inplace
7) Confirm: python flow --h

**Comment by frozenscrypt** [comment]
Hi,

I get this error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I've VS 2017 installed

**Comment by junaidwahid** [comment]
Hey @JaronrH,
I have run all the steps as you described. But, when i am running step 7 then i am getting this error "AttributeError: module 'sys' has no attribute 'getdlopenflags'"

Please help me to resolve this error

**Comment by fivecube** [comment]
@frozenscrypt 
This is the version required i think
https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409

**Comment by isharaux** [comment]
I get the following error when running
python flow --h 
`
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "D:\Quant\Backend\Qbrain2\darkflow\darkflow\cli.py", line 3, in <module>
    from .net.build import TFNet
  File "D:\Quant\Backend\Qbrain2\darkflow\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "D:\Quant\Backend\Qbrain2\darkflow\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "D:\Quant\Backend\Qbrain2\darkflow\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
`

**Comment by doduythao** [comment]
So on windows, we should also type python before flow.

**Comment by scorpionate** [comment]
> Just in case anyone else had issues getting Darkflow running on Windows 10, here's the steps that I was able to use to get it working. Hopefully it will help save time for someone else!
> 
> 1. Install Python **3.5**
> 2. [Optional] Create virtualenv
> 3. Install Tensorflow: pip3 install --upgrade tensorflow
> 4. Install cython: pip3 install cython
> 5. Install opencv: pip3 install opencv-python
> 6. Build: python setup.py build_ext --inplace
> 7. Confirm: python flow --h

I stuck at 7th. 
It says " ModuleNotFoundError: No module named 'tensorflow.contrib' "

**Comment by DhirenSc** [comment]
@maksmaxx You must have directly installed tensorflow.
Darkflow does not support tensorflow 2.0. You need to uninstall tensorflow and install it as
`pip install --upgrade tensorflow==1.15`.
I believe this should work.

**Comment by akapma** [comment]
Installing the Windows 10 most-recent SDK with additional build tools https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
and setting a path to -
`C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt`
solves the issue

**Comment by Yeaminul** [comment]
> Installing the Windows 10 most-recent SDK with additional build tools https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
> and setting a path to -
> `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt`
> solves the issue

Yes, this works! Didn't have to set the path, only installing the latest SDK worked for me. Thanks!
