### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './ckpt/checkpoint'

### ISSUE THREAD

**Issue by leekwunfung817** [thtrieu/darkflow#869]
The check point file will not generate automatically?

When I execute 
``

`python flow --model cfg/yolo.cfg --train --dataset "data\month_license" --annota
tion "data\month_license_train_data" --gpu 1.0 --load -1 --lr 0.0001 --save -16000

Parsing cfg/yolo.cfg
Loading None ...
Finished in 0.0s
Model has a coco model name, loading coco labels.

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 608, 608, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 608, 608, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 304, 304, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 304, 304, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 152, 152, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 152, 152, 128)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 152, 152, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 152, 152, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 76, 76, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 76, 76, 256)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 76, 76, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 76, 76, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 38, 38, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 19, 19, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 19, 19, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 19, 19, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 38, 38, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 64)
 Load  |  Yep!  | local flatten 2x2                | (?, 19, 19, 256)
 Load  |  Yep!  | concat [27, 24]                  | (?, 19, 19, 1280)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 19, 19, 425)
-------+--------+----------------------------------+---------------
GPU mode with 1.0 usage
cfg/yolo.cfg loss hyper-parameters:
        H       = 19
        W       = 19
        box     = 5
        classes = 80
        scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/yolo.cfg loss
Building cfg/yolo.cfg train op
2018-08-13 23:07:31.996278: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow b
inary was not compiled to use: AVX2
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "D:\A__Project\b0f8b49f22c718e99_syn\CPOS_Project\CPOS_ANPR\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "D:\A__Project\b0f8b49f22c718e99_syn\CPOS_Project\CPOS_ANPR\darkflow\net\build.py", line 76, in __init__
    self.setup_meta_ops()
  File "D:\A__Project\b0f8b49f22c718e99_syn\CPOS_Project\CPOS_ANPR\darkflow\net\build.py", line 151, in setup_meta_ops
    if self.FLAGS.load != 0: self.load_from_ckpt()
  File "D:\A__Project\b0f8b49f22c718e99_syn\CPOS_Project\CPOS_ANPR\darkflow\net\help.py", line 23, in load_from_ckpt
    with open(os.path.join(self.FLAGS.backup, 'checkpoint'), 'r') as f:
PermissionError: [Errno 13] Permission denied: './ckpt/checkpoint'

D:\A__Project\b0f8b49f22c718e99_syn\CPOS_Project\CPOS_ANPR>
`

**Comment by leekwunfung817** [comment]
1. Windows 7
2. Anacoda python
3. CPU based

**Comment by leekwunfung817** [comment]
Problem solved

put the .meta and .pd file into the ./ckpt/checkpoint, which is build by

## Saving the lastest checkpoint to protobuf file
flow --model cfg/yolo-new.cfg --load -1 --savepb

 then train it by using, 

python flow --model cfg/yolo.cfg --train --dataset "<image files>" --annotation "<annotation xml files>"
