### ISSUE TITLE
AssertionError: Loss type [softmax] not implemented

### ISSUE THREAD

**Issue by moore269** [thtrieu/darkflow#872]
I receive this error when attempting to train on 
the following cfg
https://github.com/pjreddie/darknet/blob/master/cfg/darknet19_448.cfg

I think these types of cfgs are not handled currently.

**Comment by leekwunfung817** [comment]
Can you show all the error log here?

**Comment by moore269** [comment]
Here is my command
python flow --train --model darknet19_448.cfg --load darknet19_448.weights

Here is stdout and stacktrace.

C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\dark\darknet.py:54: UserWarning: ./cfg/darknet19_448.cfg not found, use darknet19_448.cfg instead
  cfg_path, FLAGS.model))
Parsing darknet19_448.cfg
Loading darknet19_448.weights ...
Successfully identified 83427120 bytes
Finished in 0.011968851089477539s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 448, 448, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 448, 448, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 224, 224, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 224, 224, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 112, 112, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 112, 112, 128)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 112, 112, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 112, 112, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 56, 56, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 56, 56, 256)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 56, 56, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 56, 56, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 28, 28, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 28, 28, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 28, 28, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 14, 14, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 1024)
 Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 14, 14, 1000)
 Load  |  Yep!  | avgpool()                        | (?, 1000)
-------+--------+----------------------------------+---------------
Running entirely on CPU
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\net\build.py", line 76, in __init__
    self.setup_meta_ops()
  File "C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\net\build.py", line 139, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\net\help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "C:\Users\user\Downloads\darkflow-master (1)\darkflow-master\darkflow\net\vanilla\train.py", line 11, in loss
    'Loss type {} not implemented'.format(loss_type)
AssertionError: Loss type [softmax] not implemented

**Comment by moore269** [comment]
I may be wrong, but avgpool appears to be read wrong as well.
Load | Yep! | avgpool() | (?, 1000)

whereas it should be?
Load | Yep! | avgpool() | (?, 14, 14, 1000)

Maybe this contributes to the error?

**Comment by moore269** [comment]
@thtrieu any ideas?
