### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './ckpt/checkpoint'

### ISSUE THREAD

**Issue by leekwunfung817** [thtrieu/darkflow#876]
### I cannot understand about this error, I just want to make the custom
**The log will show in the following**

## Command:
python flow **--model** cfg/yolo-voc.cfg **--train** **--dataset** "PascalVOC_train_data\month_license" **--annotation** "PascalVOC_train_data
\month_license_train_data" **--gpu 1.0** **--load** -1 **--savepb** --trainer adam

## Output Log
Parsing cfg/yolo-voc.cfg
Loading None ...
Finished in 0.0s
Model has a VOC model name, loading VOC labels.

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 104, 104, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 52, 52, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 26, 26, 512)
 Load  |  Yep!  | local flatten 2x2                | (?, 13, 13, 2048)
 Load  |  Yep!  | concat [26, 24]                  | (?, 13, 13, 3072)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 125)
-------+--------+----------------------------------+---------------
GPU mode with 1.0 usage
cfg/yolo-voc.cfg loss hyper-parameters:
        H       = 13
        W       = 13
        box     = 5
        classes = 20
        scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/yolo-voc.cfg loss
Building cfg/yolo-voc.cfg train op
2018-08-15 15:52:23.547934: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\User\Documents\MachineLearning\darkflow-master\darkflow-master\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\User\Documents\MachineLearning\darkflow-master\darkflow-master\darkflow\net\build.py", line 76, in __init__
    self.setup_meta_ops()
  File "C:\Users\User\Documents\MachineLearning\darkflow-master\darkflow-master\darkflow\net\build.py", line 151, in setup_meta_ops
    if self.FLAGS.load != 0: self.load_from_ckpt()
  File "C:\Users\User\Documents\MachineLearning\darkflow-master\darkflow-master\darkflow\net\help.py", line 23, in load_from_ckpt
    with open(os.path.join(self.FLAGS.backup, 'checkpoint'), 'r') as f:
PermissionError: [Errno 13] Permission denied: './ckpt/checkpoint'

**Comment by anushabhura** [comment]
Same error has come for me too

**Comment by glare1062** [comment]
Not sure if this is too late but, 

you can get a fix here : https://stackoverflow.com/questions/13207450/permissionerror-errno-13-in-python

@anushabhura
