### ISSUE TITLE
TypeError: batch_norm() got an unexpected keyword argument 'param_initializers'

### ISSUE THREAD

**Issue by kevinkit** [thtrieu/darkflow#88]
Hello,

When I tried to run the the demo sample the following occured: 

```
root@b1ce7e66c813:~/workspace/darkflow# ./flow --test test/ --model cfg/yolo.cfg --load ../YOLO/yolo.weights --gpu 1.0
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Parsing ./cfg/yolo.cfg
Parsing cfg/yolo.cfg
Loading ../YOLO/yolo.weights ...
Successfully identified 269862452 bytes
Finished in 0.104854106903s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
Traceback (most recent call last):
  File "./flow", line 43, in <module>
    tfnet = TFNet(FLAGS)
  File "/root/workspace/darkflow/net/build.py", line 62, in __init__
    self.build_forward()
  File "/root/workspace/darkflow/net/build.py", line 82, in build_forward
    state = op_create(*args)
  File "/root/workspace/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/root/workspace/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/root/workspace/darkflow/net/ops/convolution.py", line 73, in forward
    temp = self.batchnorm(self.lay, temp)
  File "/root/workspace/darkflow/net/ops/convolution.py", line 90, in batchnorm
    return slim.batch_norm(inp, **args)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
TypeError: batch_norm() got an unexpected keyword argument 'param_initializers'


```

I tried it with the given .cfg file and with a config file from the original darknet repo - i got the error in both cases.
Any pointers whats going wrong here and how to fix it?

**Comment by thtrieu** [comment]
You sure all the dependencies (see README) are met?

**Comment by kevinkit** [comment]
Sry, i just saw that I use an old version of tensorflow - which may lead to these error.
