### ISSUE TITLE
I can't use yolo.weight

### ISSUE THREAD

**Issue by dudqls1994** [thtrieu/darkflow#880]
This is my training code . 
flow --model cfg/dudqls.cfg --load bin/yolov2.weights --labels labels1.txt --train --dataset /mnt/train2017/ --annotation /mnt/cocoxml/ --backup yolov2 --lr 1e-4 --gpu 0.7

I only change cfg file. 
classes =7 filters =60 

But Error came out ......
Parsing ./cfg/yolov2.cfg
Parsing cfg/dudqls.cfg
Loading bin/yolov2.weights ...
Traceback (most recent call last):
  File "/home/dudqls/.local/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/dudqls/.local/lib/python3.5/site-packages/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 202437760 bytes, found 203934260

How can use yolo.weight If i train 7 classes. 
Anyone Help me!!!!

**Comment by amirpr24** [comment]
Just modify the line self.offset = 16 in this file (./darkflow/utils/loader.py) and replace with self.offset = 20. save it and execute again

**Comment by maliifat** [comment]
I have to same problem …

**Comment by rimoune** [comment]
Are you keeping the original version of  yolov2.cfg in the your cfg folder? I think it needs the original one too when it sees --load bin/yolov2.weights
