### ISSUE TITLE
Error creating .pb from a custom model

### ISSUE THREAD

**Issue by satyan** [thtrieu/darkflow#91]
I'm using a model for face detection from here.. https://github.com/quanhua92/darknet/

I provided the 'labels.txt' with single entry 'face', and I see this error:

```
Traceback (most recent call last):
  File "./flow", line 59, in <module>
    tfnet.savepb(); exit('Done')
  File "/Users/satyanarayan/try/darkflow/net/build.py", line 126, in savepb
    tfnet_pb = TFNet(flags_pb, darknet_pb)		
  File "/Users/satyanarayan/try/darkflow/net/build.py", line 62, in __init__
    self.build_forward()
  File "/Users/satyanarayan/try/darkflow/net/build.py", line 82, in build_forward
    state = op_create(*args)
  File "/Users/satyanarayan/try/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/Users/satyanarayan/try/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/Users/satyanarayan/try/darkflow/net/ops/simple.py", line 88, in forward
    name = self.scope
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1924, in dropout
    name="keep_prob")
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/satyanarayan/anaconda/envs/opencvtest/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

Any suggestions on how to proceed on this one?

thanks.

**Comment by thtrieu** [comment]
Can you give the command so that I am able to reproduce this error?

**Comment by satyan** [comment]
It's the one using --savepb

./flow --model <yolo_face.cfg path> --load <yolo_face.weights path> --savepb

**Comment by thtrieu** [comment]
I am sorry for the late reply, the bug is fixed.
