### ISSUE TITLE
No module named 'darkflow.cython_utils.cy_yolo_findboxes'

### ISSUE THREAD

**Issue by kocica** [thtrieu/darkflow#914]
I've succesfully installed darkflow on the Windows 10 using the `pip install .` command. After this, I'm trying to run python flow --h, which gives me following error:

Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Users\filda\Desktop\FIT_VUT\BP\YOLO\YOLO_keras\darkflow\darkflow\cli.py", line 3, in <module>
    from .net.build import TFNet
  File "C:\Users\filda\Desktop\FIT_VUT\BP\YOLO\YOLO_keras\darkflow\darkflow\net\build.py", line 7, in <module>
    from .framework import create_framework
  File "C:\Users\filda\Desktop\FIT_VUT\BP\YOLO\YOLO_keras\darkflow\darkflow\net\framework.py", line 1, in <module>
    from . import yolo
  File "C:\Users\filda\Desktop\FIT_VUT\BP\YOLO\YOLO_keras\darkflow\darkflow\net\yolo\__init__.py", line 2, in <module>
    from . import predict
  File "C:\Users\filda\Desktop\FIT_VUT\BP\YOLO\YOLO_keras\darkflow\darkflow\net\yolo\predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

So i tried to build the Cython extensions using the `python setup.py build_ext --inplace` command, which gives me error:

c1: fatal error C1083: Cannot open source file: 'darkflow/cython_utils/nms.c': No such file or directory

May somebody tell me what am i doing wrong ?

**Comment by kocica** [comment]
I guess it would be enough if somebody could provide the darkflow/build folder for windows.
