### ISSUE TITLE
android demo error in yolov2.pb  

### ISSUE THREAD

**Issue by shenyingying** [thtrieu/darkflow#960]
@thtrieu thanks for you great job, i use darknet yolov2 train my model,the use your darkflow convert to .pb file,the use the tensorflow office android demo,in yolov2-tiny.pb it works well, but in yolov2.pb ,it throw this error 
2018-12-27 12:18:57.585 687-24128/? E/DeviceBaseImpl: [HWA_CAM3]getLaserExInfo get laser info fail
2018-12-27 12:18:57.585 23968-24102/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 23968
    java.lang.IllegalArgumentException: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1,1,256] vs. shape[13] = [0,1,1,256]
    	 [[{{node concat_2}} = ConcatV2[N=19, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_19, Reshape_20, Reshape_21, Reshape_22, Reshape_23, Reshape_24, Reshape_25, Reshape_26, Reshape_27, Reshape_28, Reshape_29, Reshape_30, Reshape_31, Reshape_32, Reshape_33, Reshape_34, Reshape_35, Reshape_36, Reshape_37, concat_2/axis)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.run(Session.java:264)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:173)

I didn't how to modify it,can you help me ,thanks a lot,can anyone help me.

**Comment by Lee-JeongMin** [comment]
How to solve this problem? 
I'm in trouble with the same problem.
