### ISSUE TITLE
Error when using "--savepb" and "--trainer adam" together

### ISSUE THREAD

**Issue by victorssilva** [thtrieu/darkflow#977]
This:

`$ flow --model cfg/tiny-yolo-voc.cfg --trainer adam --train --gpu 0.8 --dataset test/training/images --annotation test/training/annotations --savepb --epoch 20`

triggers the following:

> Traceback (most recent call last):
>   File "/home/victor/ml/bootcamp/venv/bin/flow", line 7, in <module>
>     exec(compile(f.read(), __file__, 'exec'))
>   File "/home/victor/ml/bootcamp/darkflow/flow", line 6, in <module>
>     cliHandler(sys.argv)
>   File "/home/victor/ml/bootcamp/darkflow/darkflow/cli.py", line 39, in cliHandler
>     tfnet.savepb(); exit('Done')
>   File "/home/victor/ml/bootcamp/darkflow/darkflow/net/build.py", line 161, in savepb
>     darknet_pb = self.to_darknet()
>   File "/home/victor/ml/bootcamp/darkflow/darkflow/net/help.py", line 162, in to_darknet
>     l_idx = int(var_name[0])
> ValueError: invalid literal for int() with base 10: 'beta1_power'

to_darknet seems to be trying to save Adam-related variables and barfing as they don't follow the pattern of `['22', 'convolutional/kernel']` but rather come as a list with a single value - `['beta1_power']`.

Should those be saved? If so, what would be the expected format for them?

**Comment by uwieske** [comment]
I am experiencing the same problem. I am also training with adam.  At the end of the training process the following error occurred:

<fragment of this filepath deleted>/darkflow/darkflow/net/help.py", line 162, in to_darknet
    l_idx = int(var_name[0])
ValueError: invalid literal for int() with base 10: 'beta1_power'

**Comment by NunoCalejo** [comment]
I have the same issue. Does anyone know how to solve it?

**Comment by deonis1** [comment]
You will need to add try: except ValueError in help module, "/usr/local/lib/python3.6/dist-packages/darkflow/net/help.py", line 163
